### ISSUE TITLE
How to set replay to when mail sent

### ISSUE THREAD

**Issue by PareshCitrusbug** [dacastro4/laravel-gmail#100]
I try to send a mail as a replay to inbox mail

**Comment by dacastro4** [comment]
Please add more details about your issue. You are not telling me anything.

**Comment by PareshCitrusbug** [comment]
I want to replay on a mail that receives in my inbox
when I replay to the mail that goes to the same email address where to receive. 
receiver show the mail with my inbox mail in the same thread

**Comment by dacastro4** [comment]
@PareshCitrusbug When replying, I'm taking the `Reply-To` if that's not available I'm taking the `From` header. Please check your headers and let me know

**Comment by PareshCitrusbug** [comment]
OK Works Fine

**Comment by web21moon** [comment]
I am getting the following error on replay.

I am using version 6.1

Symfony\Component\Mime\Header\Headers::addTextHeader(): Argument #2 ($value) must be of type string, null given, called in C:\xampp8\htdocs\scaleevv-web-crm\vendor\dacastro4\laravel-gmail\src\Traits\Replyable.php on line 361
