### ISSUE TITLE
error 403 Insufficient Permission with send only scope

### ISSUE THREAD

**Issue by jesephan** [dacastro4/laravel-gmail#101]
hello,

I'm having error **403 Insufficient Permission** response from google after Oauth callback when scope is set to only **send** but is fixed when using **compose** I already double-check on the google console end. Wondering if anyone here encounter this issue and could help me. 

You can see the error screenshot [here](https://prnt.sc/oiru3t).

Thanks!

**Comment by dacastro4** [comment]
It depends on what are you doing. Include the `readonly` scope

**Comment by jesephan** [comment]
@dacastro4 our app needs **send** scope only since adding **readonly** will require our app to go thru security assessment from google because that is one of the restricted scope. We want to avoid security assessment as its very costly. Any possible reason why I'm receiving such an error If I only require **send** scope? or you able to recreate this issue on your end?

**Comment by dacastro4** [comment]
I was able to replicate it.

**Comment by jesephan** [comment]
@dacastro4 good to know. I hope you can spare time helping to solve this issue. Also, I hope everyone here can contribute to fixing this bug. Mostly the use of this package is basically to send email only using gmail in my opinion. Everyone should be aware that asking for **send** only scope rather than compose will spare your app of going thru costly security assessment.

**Comment by dacastro4** [comment]
@jesephan I was able to quickly come up with a solution. The problem was that I'm requesting the email to save it in the gmail-json file and that requires a `read` permission

**Comment by jesephan** [comment]
@dacastro4 wow thank you so much you just saved me today :) more power to you!
