### ISSUE TITLE
hasAttachments not work correctly

### ISSUE THREAD

**Issue by PareshCitrusbug** [dacastro4/laravel-gmail#107]
$inbox =LaravelGmail::message()->take(config('lfk.GMAIL_PAGINATION'))->hasAttachment()->preload()->all();
                foreach ($inbox as  $message) {
                    echo $message->hasAttachments();
                }
it return null most of time

**Comment by dacastro4** [comment]
Are you preloading the mails?

**Comment by PareshCitrusbug** [comment]
Yes You can see in my Code That always return the false if the mail has attachment or not is passed true when mail sending fails or any calendar invitation 

Currently, I changed for check attachment 
$messages = LaravelGmail::message()->in()->preload()->all(null);
        foreach ($messages as  $key => $value) {
            echo $value->getSubject();
            echo "<br/>";
            $numberOfAttachments = 0;
            $files = array();
            foreach ($value->payload->parts as $part) {
                if (!empty($part->filename)) {

                    $files[] = array('filename'=>$part->filename,'mimeType'=>$part->mimeType);
                }
                if (!empty($part->body->attachmentId)) {
                    $numberOfAttachments++;
                }
            }
// dd($numberOfAttachments, $files);
        }
            
        dd("OK DONE");

**Comment by dacastro4** [comment]
I pushed some changes for the payloads yesterday. Do you mind updating to the latest version?

**Comment by PareshCitrusbug** [comment]
Yes I just updated its works fine
