### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by PareshCitrusbug** [dacastro4/laravel-gmail#111]
Hi When I try to attach the file with mail it throws me an error: Request Entity Too Large
Up to 5 MB Upload works fine
When I uploaded 10MB file then error generated 
I set my **php.ini**
upload_max_filesize=20240M
post_max_size=20240M

**Comment by dacastro4** [comment]
We said a couple of things in #77 but I think Gmail API doesn't allow files greater than 5mb if I'm not mistaken
