### ISSUE TITLE
Wrong messages being fetched

### ISSUE THREAD

**Issue by josiahmann** [dacastro4/laravel-gmail#114]
In my app I'm trying to use one of the following two code snippets and both are returning invalid results.

**Example 1**
`$messages = LaravelGmail::message()->from('ashleyshell@gmail.com)->take(5)->preload()->all();
`

returns this

<img width="1283" alt="Screen Shot 2019-08-26 at 10 51 54 AM" src="https://user-images.githubusercontent.com/6378576/64071391-29ee4d80-cc3f-11e9-9940-f2cc26851e75.png">

Trying with raw returns a messages from a completely different email as well

`$messages = LaravelGmail::message()->raw('from:ashleyshell@gmail.com OR to:ashleyshell@gmail.com')->take(5)->preload()->all();
`

Am I doing something wrong here?

**Comment by dacastro4** [comment]
@josiahmann Very sorry for the late response. Did you figure it out? I try with multiple params and they were all returning the right results. Are you taking into consideration that if the email has a response (it's a thread) I would count as a separated email?
