### ISSUE TITLE
Getting user's aliases (sending-as)

### ISSUE THREAD

**Issue by novakben** [dacastro4/laravel-gmail#120]
Awesome package,
Any ideas on how to get the logged-in user's alias addresses?
I want to present my user with a "send as" dropdown when he is composing his emails.

Also, once I have the alias can I simply use it in `$mail->from` when sending?

Thanks!

**Comment by dacastro4** [comment]
@novakben I hope you already figure this out but if you haven't: Adding the `read` scope in your config files adds the user's email to the .json config file. You can take it from there I guess.

**Comment by dacastro4** [comment]
@novakben I hope you already figure this out but if you haven't: Adding the `read` scope in your config files adds the user's email to the .json config file. You can take it from there I guess.
