### ISSUE TITLE
Configs only from .env ? 

### ISSUE THREAD

**Issue by robov** [dacastro4/laravel-gmail#123]
I would like to specify the credentials in the database, not in the .env, so that each user can get their email.
When I specify the credentials in the .env, I get a token back... yeehaa... awesome
However when I specify the credentials in the code from the database then the credentials are still used from the .env and not from the config. getconfig shows the right values
Yet in the call to gmail the .env info is used

Even when I specify in .env : GOOGLE_ALLOW_MULTIPLE_CREDENTIALS=true
..no change

Any ideas  how to specify the credentials in the code ?

`
        $config['gmail.client_id'] = $model->client_key;
        $config['gmail.client_secret'] = $model->client_secret;
        $config['gmail.redirect_url'] = $model->getCallbackUrl();

        LaravelGmail::configConstruct($config);
        $conf = LaravelGmail::getConfigs();
        return LaravelGmail::redirect();
`

**Comment by dacastro4** [comment]
The `GOOGLE_ALLOW_MULTIPLE_CREDENTIALS` works using the user's ID and create a json file from each user using the same token and same redirect URL. 
I'm not planning on adding this functionality any time soon. You can create a PR if you'd like.
