### ISSUE TITLE
Error getting message

### ISSUE THREAD

**Issue by edalzell** [dacastro4/laravel-gmail#126]
I get the following error:
```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Dacastro4\LaravelGmail\Services\Message\Mail::__construct() must be an instance of Google_Service_Gmail_Message or null, instance of GuzzleHttp\Psr7\Request given, called in /Users/erin/Sites/fitnessmd/vendor/dacastro4/laravel-gmail/src/Services/Message.php on line 126

  at /Users/erin/Sites/fitnessmd/vendor/dacastro4/laravel-gmail/src/Services/Message/Mail.php:74
    70| 	 *
    71| 	 * @param \Google_Service_Gmail_Message $message
    72| 	 * @param bool $preload
    73| 	 */
  > 74| 	public function __construct(\Google_Service_Gmail_Message $message = null, $preload = false)
    75| 	{
    76| 
    77| 		$this->service = new Google_Service_Gmail($this);
    78| 

  Exception trace:

  1   Dacastro4\LaravelGmail\Services\Message\Mail::__construct(Object(GuzzleHttp\Psr7\Request))
      /Users/erin/Sites/fitnessmd/vendor/dacastro4/laravel-gmail/src/Services/Message.php:126

  2   Dacastro4\LaravelGmail\Services\Message::get("16dd798f2f62fdb3")
      /Users/erin/Sites/fitnessmd/app/Console/Commands/GetGmailMessages.php:47
```

When I do this in code:
```php
        $messages = LaravelGmail::message()->unread()->preload()->all();

        foreach ($messages as $message) {
            $get_message = LaravelGmail::message()->get($message->getID());
```

What am I doing wrong?

**Comment by edalzell** [comment]
Neglected to say I'm on v2.0.4

**Comment by edalzell** [comment]
For some reason this:
```php
    private function getRequest($id)
    {
        return $this->service->users_messages->get('me', $id);
    }
```

returns a Guzzle Response. What the heck?

**Comment by edalzell** [comment]
I **think** this is the issue: https://github.com/googleapis/google-api-php-client/issues/1140

**Comment by dacastro4** [comment]
@edalzell I'm very sorry, I've been very busy. 
Did you try updating to the latest version or your server is not using PHP 7.3?

**Comment by edalzell** [comment]
it is the latest version of both your package and PHP (7.3).

```
        {
            "name": "dacastro4/laravel-gmail",
            "version": "v2.0.4",
            "source": {
                "type": "git",
                "url": "https://github.com/dacastro4/laravel-gmail.git",
                "reference": "f52f30e6c61f0a9f3ace79567aee594f4f902222"
            },
```

**Comment by dacastro4** [comment]
Nope, the latest version is `3.2`. I need to update the README

**Comment by edalzell** [comment]
True, but I'm on 5.8, so 2.0.4 is the latest for that: https://github.com/dacastro4/laravel-gmail/issues/126#issuecomment-557673332

**Comment by dacastro4** [comment]
Can you send me the scopes that you are using?

**Comment by edalzell** [comment]
How do I do that? Apologies I have taken over this project and there is no project documentation on what they did.

**Comment by edalzell** [comment]
FYI, I just updated to the latest and get the same error. We have also renown the auth and the gmail-json.json file got updated properly. This is the error I get:
```
erin@emdMB fitnessmd % art gmail:messages                     

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Dacastro4\LaravelGmail\Services\Message\Mail::__construct() must be an instance of Google_Service_Gmail_Message or null, instance of GuzzleHttp\Psr7\Request given, called in /Users/erin/Sites/fitnessmd/vendor/dacastro4/laravel-gmail/src/Services/Message.php on line 126

  at /Users/erin/Sites/fitnessmd/vendor/dacastro4/laravel-gmail/src/Services/Message/Mail.php:74
    70| 	 *
    71| 	 * @param \Google_Service_Gmail_Message $message
    72| 	 * @param bool $preload
    73| 	 */
  > 74| 	public function __construct(\Google_Service_Gmail_Message $message = null, $preload = false)
    75| 	{
    76| 
    77| 		$this->service = new Google_Service_Gmail($this);
    78| 

  Exception trace:

  1   Dacastro4\LaravelGmail\Services\Message\Mail::__construct(Object(GuzzleHttp\Psr7\Request))
      /Users/erin/Sites/fitnessmd/vendor/dacastro4/laravel-gmail/src/Services/Message.php:126

  2   Dacastro4\LaravelGmail\Services\Message::get("16eae68fcb241104")
      /Users/erin/Sites/fitnessmd/app/Console/Commands/GetGmailMessages.php:49

  Please use the argument -v to see more details.
```

**Comment by dacastro4** [comment]
This
```	
'scopes' => [
  'compose',
  'insert',
  'labels',
  'send',
  'readonly',
],
```
That's what I have on my `config/gmail.php`

**Comment by edalzell** [comment]
```
	'project_id' => env('GOOGLE_PROJECT_ID'),
	'client_id' => env('GOOGLE_INBOUND_CLIENT_ID'),
	'client_secret' => env('GOOGLE_INBOUND_CLIENT_SECRET'),
	'redirect_url' => env('GOOGLE_REDIRECT_URI', '/'),

	'state' => null,

	'scopes' => [
		'readonly',
		'labels',
		'modify'
	],
```

**Comment by dacastro4** [comment]
Can you try with the ones that I sent? Remember to logout and login again (Gmail)

**Comment by edalzell** [comment]
we're not composing, nor inserting nor sending though, are those required?

And log in out of the email account?

I will get the client to try, thanks for your attention and patience!

**Comment by dacastro4** [comment]
I just want to try something out because I have no clue why this is happening to you. I copied your example and seems to be working for me.

> And log in out of the email account?

Yes

**Comment by edalzell** [comment]
Unfortunately no change. We’ve got the original devs (of the app) looking in to it now as it used to work. 

It’s really strange just before the above call it is what it is supposed to be but it seems to get converted into a request.

**Comment by dacastro4** [comment]
I'll try something else when I can.

**Comment by edalzell** [comment]
I apologize, the code throwing this error is:
```
        $messages = LaravelGmail::message()->unread()->preload()->all();
```

**Comment by dacastro4** [comment]
Now that I'm paying more attention and I'm sorry that I didn't before, why are you doing that? If you preload the message, your `$message` variable is already the full message with the body, subject, and everything. I was able to fix this issue but now I realize the way the developer did it the first time is a waste of calls to the Google API (wasting more money)

**Comment by edalzell** [comment]
I realized that as well after I traced through the code a bit more closely. Saw that batch var then realized the second call wasn’t needed. 

Thanks for your attention and this is a great package!

**Comment by dacastro4** [comment]
@edalzell thank you!
