### ISSUE TITLE
how to create new labels ? 

### ISSUE THREAD

**Issue by giojkd** [dacastro4/laravel-gmail#127]
Can I create new labels?

**Comment by SimonMuraya** [comment]
@giojkd i think the method below can do..

```
//Add multiple or single label to the email
$mail->addLabel($string|$array) 
```
Reference: https://github.com/dacastro4/laravel-gmail/blob/master/readme.md

If the above doesn't satisfy your expectation you can always refer tp the link below;
https://developers.google.com/gmail/api/v1/reference/users/labels/create

**Comment by dacastro4** [comment]
@giojkd  I don't have that feature but I have a workaround for you
Get a single message and access the service from it
```
$message->service->users_labels->create()
```
And then you can follow the instructions on the link that @SimonMuraya  posted.
I hope this helps
