### ISSUE TITLE
No credentials found.

### ISSUE THREAD

**Issue by rsmith87** [dacastro4/laravel-gmail#13]
Dacastro4\LaravelGmail\Exceptions\AuthException
No credentials found.

I've renamed the env variable of 'credentials_file_name' => env( 'GOOGLE_CREDENTIALS_NAME', 'client.json') with the downloaded file from Google stored in the root of my directory.

Any advice on this?  Thanks a bunch for your work on this!

**Comment by rsmith87** [comment]
Whoops.  I figured out where you've configured the directory to store this.

For future reference, defaults to storage/app/gmail/tokens

**Comment by dacastro4** [comment]
Glad you figured it out!

**Comment by landes01** [comment]
how can we generate the gmail / tokens folder in storage / app / gmail / tokens
I use laravel 5.7
I did the update but nothing.

**Comment by ojha007** [comment]
i got the same issue

**Comment by redaTaha95** [comment]
I have the same problem can someone help, please !!

**Comment by redaTaha95** [comment]
> Whoops. I figured out where you've configured the directory to store this.
> 
> For future reference, defaults to storage/app/gmail/tokens

Can u help us to solve this problem

**Comment by hirenpatel1903** [comment]
I am facing same issue, anyone HELP me !!

![image](https://user-images.githubusercontent.com/47753427/183667700-5345e543-7861-46cc-8cf1-4370696a4ee0.png)

**Comment by nikhilbhatt10798** [comment]
I am having same issue kindly help 
![Screenshot 2022-12-20 144456](https://user-images.githubusercontent.com/83267123/208629430-a3383d2f-9948-494c-bffd-bd9bd697dc8b.png)
