### ISSUE TITLE
Link custom Login to the lib

### ISSUE THREAD

**Issue by frenchqwerty** [dacastro4/laravel-gmail#132]
Hi,

I am working on a CMS and I have a problem. I have a custom Login and I want to add the Google OAuth for sending mail. I have tryied to set the GOOGLE_ALLOW_MULTIPLE_CREDENTIALS to `true`, but the `LaravelGmail::check()` return false.

How can I link LaravelGmail login with my custom login ?

There are some code :

web.php
```
//Route Authentification
Route::post('login', 'User\UserController@login')->name('login');
Route::post('register', 'User\UserController@register')->name('register');

//Route Google OAuth
Route::get('/oauth/gmail', 'User\UserController@loginWithGoogle')->name('loginWithGoogle');
Route::get('/oauth/gmail/callback', 'User\UserController@callbackAfterLoginWithGoogle')->name('callbackAfterLoginWithGoogle');
Route::get('/oauth/gmail/logout', function (){
    LaravelGmail::logout(); //It returns exception if fails
    return redirect()->to('/');
});
```

UserController.php

```
public function login()
    {
        if (Auth::attempt(['email' => request('email'), 'password' => request('password')]))
        {
            $user = Auth::user();
            $success['token'] = $user->createToken('MyApp')->accessToken;
            return response()->json(['success' => $success], $this->successStatus);
        }
        else
        {
            return response()->json(['error' => 'Unauthorised'], 401);
        }
    }

    public function loginWithGoogle()
    {
        return LaravelGmail::redirect();
    }

    public function callbackAfterLoginWithGoogle()
    {
        LaravelGmail::makeToken(); //It returns exception if fails
        return redirect()->to('/');
    }
```

**Comment by frenchqwerty** [comment]
Edit : When I remove the `LaravelGmail::check()`, I have a Exception with : `Login required`
I have checked `storage/app/gmail/tokens/gmail-json.json` and the file exist...
`GOOGLE_ALLOW_MULTIPLE_CREDENTIALS=true` doesn't work, if I set that at `false`, it's works ! 
So, I have tried to disconnect and reconnect with another account but gmail-json.json doesn't change and when I send an email, the sender is not the user reconnected...

**Comment by dacastro4** [comment]
Hey @frenchqwerty can you specifically tell me what's the issue with the package? `GOOGLE_ALLOW_MULTIPLE_CREDENTIALS` only works when the user it's already logged in with your app. If you want to allow users to sign up with Google, this is not the right package for you.

**Comment by frenchqwerty** [comment]
@dacastro4 Thanks for quickly reply.
I want to send and display mail in my CRM with account Google. I have implemented your package and it's work. But I want to give the possibility of multiple credentials.

If User A is connected with your package and can send mail normally.
Now, User B want to send mail with his account Google, he can call the package for connect with his account Gmail and send mail with his account.

How can I do that ?

Sorry it's hard for me to explain correctly.

**Comment by dacastro4** [comment]
@frenchqwerty they have to log in to your app first and then do a "connect your google account" type of thing and that would work

**Comment by frenchqwerty** [comment]
@dacastro4 I have already do that and 
If I set `GOOGLE_ALLOW_MULTIPLE_CREDENTIALS` to `true`, I have a I have an Exception with : `Login required`. 
Else if I set `GOOGLE_ALLOW_MULTIPLE_CREDENTIALS `to `false`, I can send mail but, it send the mail with the wrong user.
Tomorrow I will try again, If I can't, I will show you my code. Thanks for your time. 

Have a nice day

**Comment by frenchqwerty** [comment]
@dacastro4 Hi, I'm back,
I have the same issue, so I have tried to set `GOOGLE_ALLOW_MULTIPLE_CREDENTIALS` to `false` and set the sender with `$mail->from() `for emulate the behavior excepted but it doesn't work.
My code : 
```
if (!LaravelGmail::check())
            return response()->json(['error' => 'You must be logged with Google'], 401);
        $mailPayload = $validator->validated();
        $mail = new Mail;

        $agent = Auth::user();
        $mail->to($mailPayload['mail_to']);
        $mail->from("demo@demo.com"); // the sender is not set to demo@demo.com
        $mail->subject($mailPayload['mail_object']);
        $mail->message($mailPayload['mail_content']);
        $mail->send();
```

I don't know why your package doesn't set the sender. I just want to send mail with an account set dynamically

**Comment by damms005** [comment]
I must mention that most of the issues are because of the way this package is documented. I hope will welcome a rewrite/improvement on the current documentation. E.g., the `credentials_file_name` part of the configuration file reads:

```
	/*
	|--------------------------------------------------------------------------
	| Credentials File Name
	|--------------------------------------------------------------------------
	|
	|   :email to use, clients email on the file
	|
	|
	*/

	'credentials_file_name' => env('GOOGLE_CREDENTIALS_NAME', 'gmail-json'),

```

Now in the above, `:email to use, clients email on the file` is very ambiguous. Does it mean the json is a key-value pair of users and their configuration? etc...
