### ISSUE TITLE
HTTP 500 'Login is required' on emailing with multiple user credentials configuration

### ISSUE THREAD

**Issue by GiMitch** [dacastro4/laravel-gmail#133]
Greetings,

Knowing that all my application users are using company email (gmail emails), I am developing an Laravel API which must be able to sends email as the currently logged user.

Following the documentation, while I was able to send email using the 'single user credential' approach, when trying to configure the wrapper so it could support multiple user credentials (by setting `GOOGLE_ALLOW_MULTIPLE_CREDENTIALS` to true), any attempt to send a email raises an _**HTTP 500 Google_Service_Exception**_ :
```
{
   "error":{
      "errors":[
         {
            "domain":"global",
            "reason":"required",
            "message":"Login Required",
            "locationType":"header",
            "location":"Authorization"
         }
      ],
      "code":401,
      "message":"Login Required"
   }
}
```
Additional information :
- the scope was defined to ``all``

**Comment by dacastro4** [comment]
Did you try #83?
