### ISSUE TITLE
PHP 7.4: During class fetch: Uncaught ErrorException: Unparenthesized `a ? b : c ? d : e` is deprecated.

### ISSUE THREAD

**Issue by bakoe** [dacastro4/laravel-gmail#134]
### Actual

When using the module in a Laravel project with PHP 7.4.0, the following Exception is being thrown:

```php
PHP Fatal error:  During class fetch: Uncaught ErrorException: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /absolute/path/to/project/vendor/dacastro4/laravel-gmail/src/Traits/Filterable.php:62
```

### Expected

No such Exception should be thrown when using PHP 7.4.0.

### Details

The Exception is apparently caused by the [ternary statement in `src/Traits/Filterable.php:62`](https://github.com/dacastro4/laravel-gmail/blob/master/src/Traits/Filterable.php#L62).

**Comment by dacastro4** [comment]
Hey @bakoe I should fix the readme now because I haven't tested it on PHP 7.4 and apparently it is not compatible.

**Comment by simaodiascosta** [comment]
Hey @dacastro4. 

As the error message suggests, doing this change, the error is fixed. Tested here.

**src/Traits/Filterable.php:62.**
`! $i ? $this->add( "{from:$emails[$i]" ) : $i == $emailsCount - 1 ? $this->add( "from:$emails[$i]}" ) : $this->from( $emails[ $i ] );`

`! $i ? $this->add( "{from:$emails[$i]" ) : ($i == $emailsCount - 1 ? $this->add( "from:$emails[$i]}" ) : $this->from( $emails[ $i ] ));`

**Comment by Vinze** [comment]
Could the fix from @simaodiascosta also be applied to version 3.0? I'm using Laravel 6 with PHP 7.4 and also getting this exception.
