### ISSUE TITLE
How to send an email?

### ISSUE THREAD

**Issue by rsmith87** [dacastro4/laravel-gmail#14]
Thanks again for the awesome package.  I'm having troubles sending an email because I don't know what I should be instantiating it with.  Current code (that doesn't work):

      $mail = LaravelGmail::message()->to($data['to'])->from('someting@foo.com')->subject($subject)->message($texteditor)->send();
 
I don't think this is it.. Haha.  

Would you have any objections to having some helpers to tie it to an existing email in App\User ? I have some updated code that's working for me and I don't mind putting in a PR for it.

**Comment by dacastro4** [comment]
Hey @rsmith87. You should import the Mail class from my package and the code would be `$mail = new Mail->to($data['to'])->from('someting@foo.com')->subject($subject)->message($texteditor)->send();`. I forgot to put some code example of how to send and email, my bad.

**Comment by rsmith87** [comment]
Ah perfect!  Thanks!  No worries on the documentation, I was getting close as i was fishing in Replyable.  Thanks for being so responsive!

**Comment by usamasarfraz143** [comment]
Call to undefined method Illuminate\Support\Facades\Mail::to() (View: C:\xampp\htdocs\mygoogleapi\resources\views\welcome.blade.php)

**Comment by usamasarfraz143** [comment]
using this classmail class 
 Call to undefined method Illuminate\Support\Facades\Mail::to() (View: C:\xampp\htdocs\mygoogleapi\resources\views\welcome.blade.php)

**Comment by dacastro4** [comment]
@usamasarfraz143 can you show me your code, please?

**Comment by usamasarfraz143** [comment]
@dacastro4  thanx i figure it out

**Comment by sahakavatar** [comment]
Hey @dacastro4 .
How can I get email id after send email 
 $mail = LaravelGmail::message()->to($data['to'])->from('someting@foo.com')->subject($subject)->message($texteditor)->send();
$mail->getId()  return null 
https://www.screencast.com/t/NqH6xpZC

**Comment by tibinmathew007** [comment]
@usamasarfraz143 how you fixed it?

**Comment by shashankj99** [comment]
@dacastro4 hey I couldn't figure it out... need help it's urgent i'm approaching my project deadline

**Comment by jmatembu** [comment]
@shashankj99, there is already an example of how to send an email in this same issue. See @dacastro4's reply above. If you have tried the same and still not working, you may have to show some pieces of your code.
