### ISSUE TITLE
Restoring access without user authentication - long-lived tokens?

### ISSUE THREAD

**Issue by joewardpr** [dacastro4/laravel-gmail#141]
A user authenticates and grants permissions. They have a temporary token.

How do we restore that access on the server side to (for example) send a scheduled message without the user present to grant permissions through the browser again?

1. Do we need to save the refreshToken locally and restore it somehow?
2. Or does it store that token automatically and we just set the ID (email) of the user to have code handle getting a token itself?

**Comment by dacastro4** [comment]
You have to check Gmail's documentation but I don't think there's a way to do that. Defeats the purpose and would have security issues.

**Comment by usamanoman** [comment]
@joewardpr  were you able to figure this out?

**Comment by chrisworrell** [comment]
@dacastro4 does this library not support server-side authorization where when a user grants access we can then save the users refresh token so that we could do future requests on that users behalf when they are not logged in?  I believe that is what the original person was asking
