### ISSUE TITLE
How to receive 5 most recent emails

### ISSUE THREAD

**Issue by jstam89** [dacastro4/laravel-gmail#148]
I recently started with this and now I would like some help to find out how i can receive the latest receiven emails read and unread. anyone willing to help a poor ol boi?

**Comment by blankRSD** [comment]
You can use the raw method to use filters. For example: 
For getting all unread messages in inbox
`$mails = LaravelGmail::message()->raw('in:inbox is:unread')->preload()->all();`
For getting all read messages in inbox
`$mails = LaravelGmail::message()->raw('in:inbox is:read')->preload()->all();`

You can test out the correct filters by using them in the Gmail search box. 
For more info: [Link](https://support.google.com/mail/answer/7190?hl=en)

**Comment by jstam89** [comment]
Thank you! I will try this give feedback and close if it's fixed.  Appreciate your answer!

**Comment by jstam89** [comment]
It does get my unread emails but I'm getting an empty object as subject and body.

**Comment by blankRSD** [comment]
Did you use the `preload()` function? Preload fetches all the content of mail as mentioned in the README.

**Comment by jstam89** [comment]
I did as you said. I'm getting a payload with sometimes 60 objects.. I've clicked trough 1 and found a subject somewhere.. but the actual data is not presenting a subject and body.

**Comment by blankRSD** [comment]
If you want to reduce the number of mails you can use the `take()` function.
Eg: 
`$mails = LaravelGmail::message()->raw('in:inbox is:unread')->take(5)->preload()->all();`

After this, you can run a foreach loop on `$mails` to get the content as mentioned [here](https://github.com/dacastro4/laravel-gmail#mail)
Eg:
```
foreach($mails as $mail){
    echo $mail->getSubject();
    echo $mail->getHtmlBody();
}
