### ISSUE TITLE
Login Required

### ISSUE THREAD

**Issue by khavishbhundoo** [dacastro4/laravel-gmail#149]
I am getting the following error while sending emails

`{ "error": { "errors": [ { "domain": "global", "reason": "required", "message": "Login Required", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Login Required" } }
`

I added your library and modified the env as follows

```
GOOGLE_PROJECT_ID=from credential json
GOOGLE_CLIENT_ID=from credential json
GOOGLE_CLIENT_SECRET=from credential json
GOOGLE_REDIRECT_URI=
GOOGLE_ALLOW_MULTIPLE_CREDENTIALS
GOOGLE_ALLOW_JSON_ENCRYPT
```

There is the quickstart php found in google docs but since here we won't be using the credentials json since we are using env variable , can your library expose the login as well?

**Comment by giennjoro** [comment]
@khavishbhundoo I think the error you are having is related to one I have. I have realized that upon allowing the app to access mail information, it redirects successfully but the welcome page (updated as per the documentation), still reads login. I think the login action is not being handled correctly.
@dacastro4 please attend to this.

**Comment by giennjoro** [comment]
I figured out the problem. Ensure, that the gmail-json.json is present.

**Comment by khavishbhundoo** [comment]
@giennjoro  Can you share the content of  gmail-json.json with fake details.I created an empty one and it still didn't work
