### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by joannesnoel** [dacastro4/laravel-gmail#15]
hello dacastro4,

is there a way to have a refresh token so that the auth does not expire? i dont want to keep re-authenticating Gmail. thanks!

regards,
Joannes

**Comment by dacastro4** [comment]
Hey! I'm sorry for the delay. It should do it automatically. Which file system driver are you using?

**Comment by buisine** [comment]
Hi,
also having same issue, token is never refreshed and i have to re-auth with google again and again.
Running on localhost now, token file exists in 

storage/app/gmail/tokens

and my file system driver is : 

env('FILESYSTEM_DRIVER', 'local')

thanks

**Comment by dacastro4** [comment]
@buisine does your file has a structure like this? 
```json
{
    "access_token":"*access_token*",
    "token_type":"Bearer",
    "expires_in":3600,
    "refresh_token":"*refresh_token*",
    "created":1522885414,
    "email":"email"
}
```

**Comment by keyurgwebplanex** [comment]
Hello, 
How to refresh token?
