### ISSUE TITLE
Error from Google api

### ISSUE THREAD

**Issue by VladimirAfonin** [dacastro4/laravel-gmail#153]
Hi, i get error: "HTTP Batch endpoint is deprecated. See https://g.co/cloud/global-batch-deprecation for info and migration steps". This error in file -> vendor/google/apiclient/src/Google/Http/REST.php::118. I realized it will be disconnected soon

**Comment by VladimirAfonin** [comment]
some addition: i got this error when i call -> " LaravelGmail::message()->unread()->preload()->all(); ".

**Comment by dacastro4** [comment]
@VladimirAfonin Please let me know. I updated the Google API services version. If that doesn't do the job, reopen the issue.

**Comment by VladimirAfonin** [comment]
Thank you! Now it works correctly, there are no "deprecated" errors. If errors occur, I will let you know.

**Comment by VladimirAfonin** [comment]
Hi, i still same error: [2020-06-30 10:55:56] Ошибка : tyest303@gmail.comGlobal HTTP Batch endpoint is deprecated. See https://g.co/cloud/global-batch-deprecation for info and migration steps./var/www/api/vendor/google/apiclient/src/Google/Http/REST.php118

**Comment by VladimirAfonin** [comment]
Some addition: 
![DeepinScreenshot_select-area_20200630144031](https://user-images.githubusercontent.com/22343015/86122019-b8da2980-badf-11ea-950a-2e113391fec2.png)

**Comment by VladimirAfonin** [comment]
I did not find an opportunity to reopen this issue therefore I created a new one #154
