### ISSUE TITLE
How I can automatically fetch a new message With a specific Subject?

### ISSUE THREAD

**Issue by kvachakhia** [dacastro4/laravel-gmail#155]
**How I can automatically fetch a new message With a specific Subject?**

**Comment by kvachakhia** [comment]
@dacastro4  Please help me

**Comment by dacastro4** [comment]
You can use the `subject` method but you might find more than one. Do something like `subject('my subject')->take(1)->all()`

**Comment by kvachakhia** [comment]
> You can use the `subject` method but you might find more than one. Do something like `subject('my subject')->take(1)->all()`

But this fetching only if I refresh page... I want If come new message fetch automatically because I need save in database... Have any idea ? 🤔

**Comment by veed76** [comment]
Hi @kvachakhia 
Have you got a solution? 
How can I auto receive new emails?

**Comment by kvachakhia** [comment]
> Have you got a solution?

Yes Cron job

**Comment by veed76** [comment]
@kvachakhia 
Just now I found the solution, if you create the subscription in pub/sub then you will automatically receive the new email.
the pub/sub work seems like a webhook.

**Comment by veed76** [comment]
<img width="898" alt="Screenshot 2020-08-06 at 11 44 25 PM" src="https://user-images.githubusercontent.com/20658698/89567130-c69d7000-d83e-11ea-9018-87a23a42ba24.png">
See the attachment

**Comment by kvachakhia** [comment]
> @kvachakhia
> Just now I found the solution, if you create the subscription in pub/sub then you will automatically receive the new email.
> the pub/sub work seems like a webhook.

It's Good bu I have cron job, for example, searching last Mail ID and if not exist creating

**Comment by phuclh** [comment]
> <img alt="Screenshot 2020-08-06 at 11 44 25 PM" width="898" src="https://user-images.githubusercontent.com/20658698/89567130-c69d7000-d83e-11ea-9018-87a23a42ba24.png">
> 
> See the attachment

@veed76  Can you help me on that? I still have trouble when receiving data from pub/sub.

**Comment by afrazahmmad** [comment]
Can anybody share the procedure to use pub/sub
thanks
