### ISSUE TITLE
getting gmail messages

### ISSUE THREAD

**Issue by siegfriedsutanto** [dacastro4/laravel-gmail#16]
I am trying to test this code on my controller 
$messages = LaravelGmail::message()->all( $pageToken = null );
var_dump($messages);
but i get this message
Dacastro4\LaravelGmail\Services\Message and Dacastro4\LaravelGmail\Traits\SendsParameters define the same property ($params) in the composition of Dacastro4\LaravelGmail\Services\Message. However, the definition differs and is considered incompatible. Class was composed

**Comment by siegfriedsutanto** [comment]
fixed... need to delete 
use SendsParameters;

**Comment by dacastro4** [comment]
I'm going to take a look at this because you definitely should not remove that trait. Thank you

**Comment by anibalealvarezs** [comment]
Got the same error here when testing your Blade example:

'Dacastro4\LaravelGmail\GmailConnection and Dacastro4\LaravelGmail\Traits\Configurable define the same property ($configuration) in the composition of Dacastro4\LaravelGmail\GmailConnection. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed' in /home/sistemabidorg/vendor/dacastro4/laravel-gmail/src/GmailConnection.php:193

**Comment by anibalealvarezs** [comment]
Since it's a private property, i jut changed the name:

`private $configuration;` to `private $configurate;`
`$this->configuration = $config;` to `$this->configurate = $config;`

**Comment by dacastro4** [comment]
@anibalealvarezs  @siegfriedsutanto I recently pushed some code that should fix this. Let me know please

**Comment by dacastro4** [comment]
I'm gonna close this issue. Feel free to reopen it if you keep getting the same error.

**Comment by dacastro4** [comment]
I'm gonna close this issue. Feel free to reopen it if you keep getting the same error.
