### ISSUE TITLE
Ordering the messages from newest to oldest

### ISSUE THREAD

**Issue by JeanHules** [dacastro4/laravel-gmail#17]
I am getting the messages, but it is pulling the oldest emails first. Is there a way to pull the latest emails first?

**Comment by dacastro4** [comment]
Hey @JeanHules. AFAIK there's no way to sorted with oldest first but you can check more query parameters [here](https://support.google.com/mail/answer/7190?hl=en).
and you can use it doing: 
```LaravelGmail::message()->subject('test')->unread()->add('before:2004/04/18')->all()```
