### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by coolashelvetica** [dacastro4/laravel-gmail#18]
I am getting the following error once I log into my Gmail account and redirect back to the app URL

Dacastro4\LaravelGmail\Services\Message and Dacastro4\LaravelGmail\Traits\SendsParameters define the same property ($params) in the composition of Dacastro4\LaravelGmail\Services\Message. However, the definition differs and is considered incompatible. Class was composed

Any ideas?

**Comment by dacastro4** [comment]
Hey, @coolashelvetica! Sorry for the delay.

I couple days before you opened this issue I pushed some code that should resolve this issue. Please let me know If pulling the latest code helps you.
