### ISSUE TITLE
Can't install v5.1 with PHP 8.0 - new release required

### ISSUE THREAD

**Issue by robfrancken** [dacastro4/laravel-gmail#182]
It looks like something is wrong on packagist.org, it's expecting php7.2 with version 5.1. I'm guessing you need to create tag 5.2 because the pull request updating the composer.json dependencies came on 9 Jan, and 5.1 was release on 8 Jan.

![image](https://user-images.githubusercontent.com/14947976/110442311-70f7b180-8106-11eb-8ca2-7d2910da496b.png)

**Comment by dacastro4** [comment]
Thanks
