### ISSUE TITLE
Read messages & attachments while allow multiple credentials

### ISSUE THREAD

**Issue by mzaalan** [dacastro4/laravel-gmail#187]
I have Auth error while fetching message when multiple credentials enabled, The problem is that userId not passed to "Dacastro4\LaravelGmail\Services\Message\Mail" class when create new instances from "Dacastro4\LaravelGmail\Service\Message" class.
Also same problem regarding to attachments. So I have just pass new parameter to Attachment Class and then pass to parent constructor.

**Comment by mzaalan** [comment]
I have already create this PR:
https://github.com/dacastro4/laravel-gmail/pull/186

**Comment by dacastro4** [comment]
Merged. Thanks
