### ISSUE TITLE
Reply to existing messages 

### ISSUE THREAD

**Issue by Onderi** [dacastro4/laravel-gmail#19]
Here is my code

 public function inbox(){
            $messages = LaravelGmail::message()->unread()->preload()->all();

            foreach ( $messages as $message ) {
            $subject = $message->getSubject();
            $body = $message->getPlainTextBody();
            $fromname= $message->getFromName();
            $fromemail= $message->getFromEmail();
            
            $mail =$message ->markAsRead();
            $mail=$message ->reply('recieved')->send();

I get an error 

"invalidArgument", "message": "Recipient address required" } ], "code": 400, "message": "Recipient address required" } }

**Comment by dacastro4** [comment]
Hey @Onderi.
Check the [sending](https://github.com/dacastro4/laravel-gmail#sending) of the documentation. You're missing the "->to()" with the recipient and more but that the only required thing.

**Comment by Onderi** [comment]
Thanks for your reply..

Kindly help me spot the error in the code below.

 $mail= $message-> reply()->to($fromemail);


Kind regards

**Comment by dacastro4** [comment]
Hey @Onderi 
The problem is in the order. The `reply` method is the action that sends the actual email, that said your code should be `$mail= $message->to($fromemail)->reply();`

**Comment by Onderi** [comment]
It worked!!!!
Thank you so much.
Regards.
