### ISSUE TITLE
Class 'Dacastro4\LaravelGmail' Not Found

### ISSUE THREAD

**Issue by qmix21** [dacastro4/laravel-gmail#20]
Hey

Trying to set this up in my controller but am unable to due to error when adding "use Dacastro4\LaravelGmail;" I have followed the README.md to the bone and am unable to see where i went wrong....

Using laravel version 5.6

**Comment by dacastro4** [comment]
Hey @qmix21 can you show the error and the code that you're trying to run, please?

**Comment by qmix21** [comment]
Error:
`Class 'Dacastro4\LaravelGmail' not found`


ReportController.php

```
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Dacastro4\LaravelGmail;

class ReportController extends Controller
{
public function index()
{
return LaravelGmail::message()->all;
}

}
```





config/app.php:
```
'providers'=>[

.....
Dacastro4\LaravelGmail\LaravelGmailServiceProvider::class,
.....
]

'aliases' => [
...
    'LaravelGmail' => Dacastro4\LaravelGmail\Facades\LaravelGmail::class,
...
]
```


web.php:

```Route::get('/','ReportController@index');```

**Comment by JonahKlimack** [comment]
I hate to say me too, but... me too.

laravel 5.3.31

controller is

```
<?php

namespace App\Http\Controllers;


use LaravelGmail;
use Illuminate\Http\Request;

class TestGmailApiController extends Controller
{
	/**
	 * testing
	 *
	 * @return void
	 */
	public function test ()
	{
		return LaravelGmail::getAuthUrl;

	}

}

```

same config/app.php as @qmix21 

error is:

ErrorException in AliasLoader.php line 66:
Class 'Dacastro4\LaravelGmail\Facades\LaravelGmail' not found



in the vendor folder, folder names are  dacastro4/laravel-gmail...

**Comment by JonahKlimack** [comment]
fixed here: https://github.com/dacastro4/laravel-gmail/issues/12

**Comment by dacastro4** [comment]
@JonahKlimack that's right. Totally my bad. Time to update the readme.

**Comment by azhar007elhar** [comment]
Class 'Dacastro4\LaravelGmail' not found
