### ISSUE TITLE
Do we need to enable any restricted scope in Google App to just read/send emails ?

### ISSUE THREAD

**Issue by afrazahmmad** [dacastro4/laravel-gmail#201]
Hi dear!
Thanks a lot for the great utility package.

I just want to fetch and send emails/replies. So do we need any restricted scope permissions to make it work ?
Right now my app does not have permission to any restricted scope.

Thanks and regards,
Afraz Ahmad

**Comment by cvsoftexp** [comment]
Yes, you'll need restricted scope and go through the verification process https://support.google.com/cloud/answer/9110914
