### ISSUE TITLE
feature request: ->take(5)  or ->some(5) instead of all()

### ISSUE THREAD

**Issue by JonahKlimack** [dacastro4/laravel-gmail#21]
Love how you structured all of this.  This has definitely saved me a ton of setup time to work with gmail api.

But as you said, it's a work in progress.

For my use case, the current filters aren't adequate enough to limit my query.

Currently this returns 100 messages and it takes a long time if I want to loop through them.

```
$messages = LaravelGmail::message()->from('some@email.com')->all();
```

if I do this, it takes like 1 second:

```
$messages = LaravelGmail::message()->from('some@email.com')->all();
dump($messages);
```

this times out...

```
$messages = LaravelGmail::message()->from('some@email.com')->preload()->all();
dump($messages);
```

  doing this takes 17 seconds..... 

```

		$messages = LaravelGmail::message()->from('some@email.com')->all();

		$count = 0;
		foreach ($messages as $message) 
		{
			// $body = $message->getHtmlBody();
			$subject = $message->load()->getSubject();

			dump($subject);
			// dump($body);

			if ($count > 5)
				break;
			else
				$count++;
		}
	

```

What if we could do this?
```
$messages = LaravelGmail::message()->from('some@email.com')->preload()->take(5);
```

The goal being to increase performance?

Or am I missing something really obvious? Like some date filters...

**Comment by dacastro4** [comment]
Thank you, @JonahKlimack .
I think that's a great idea. I'll push that method in a little bit.
Also, I  know we have the `preload` method but in reality, we should not preload a bush of emails at the same time because of what you mention, the performance.

**Comment by dacastro4** [comment]
@JonahKlimack  I'm glad it helped and don't worry about that, we are all noobs at some point, right? I'll be expecting your PR's.
