### ISSUE TITLE
$message()->preload()->all(); doesn't return all emails

### ISSUE THREAD

**Issue by qmix21** [dacastro4/laravel-gmail#23]
Hey, I love your API, its great. However when trying to run it through all of my emails it only returns 99 instead of all of them(at this time is at 1300+). Is there a limit set somewhere that may be limiting it to 99 or is there an issue?

See below login from controller:
```

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use LaravelGmail;
class ReportController extends Controller
{
    
    public function mail()
    {
        $messages = LaravelGmail::message()->preload()->all();
        #return $messages[0]->payload->parts[0]->body->data;
        $subjects = $this->getSubject($messages);
        return $subjects;
    }

    //This function will loop through all of the headers to find the subject and returns the array of subjects.
    public function getSubject($messages)
    {
    	$arr = array();
    	foreach($messages as $m)
    	{
    		foreach($m->payload->headers as $h)
    		{
    			if($h->name == 'Subject')
    			{
    				array_push($arr, $h->value);
    			}
    		}

    	}
    	return $arr;
    }

    
}

```

I Attempted in using your take() function but it doens't seem to increase the limit...

**Comment by JonahKlimack** [comment]
Hi

First of all, this might be easier and does the same thing?

```

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use LaravelGmail;

class ReportController extends Controller
{

	public function mail()
	{
		$messages = LaravelGmail::message()->preload()->all();
                //dd($messages);

		foreach ( $messages as $message )
			$subjects[] = $message->getSubject();
		
		return $subjects;
	}
}

```

Second,  how many items does it say the collection has, when you run the above and uncomment dd($messages)  line ?

**Comment by dacastro4** [comment]
Hey @qmix21 this [link](https://stackoverflow.com/questions/43269704/gmail-api-getting-all-gmail-inbox-messages-limits-to-500) may help you. I think I can't get all the emails because of Gmail restrictions.
@JonahKlimack thanks for the help.
