### ISSUE TITLE
Getting error while replying to email

### ISSUE THREAD

**Issue by web95-moon** [dacastro4/laravel-gmail#259]
I am getting error while replying to email with this package.

Symfony\\Component\\Mime\\Header\\Headers::addTextHeader(): Argument #2 ($value) must be of type string, null given,
 
 Below is the code screenshot that i am doing 
 
 
![image](https://user-images.githubusercontent.com/125456979/236859482-77252c10-b42e-4471-9164-5efe1ff461cf.png)

I have also check source code and where i found problem is stated in below screenshot. Getting null for "References" Header.

![image](https://user-images.githubusercontent.com/125456979/236859834-b11a0c8d-7cf0-4d2c-adc8-58b124f85a53.png)

Any help is appreciated.

**Comment by web95-moon** [comment]
![image](https://github.com/dacastro4/laravel-gmail/assets/125456979/e4eaf2a6-2423-428f-822b-2d1a53cf5435)

**Comment by web95-moon** [comment]
php version:- 8.0.2
Laravel version:- 9.19
dacastro4/laravel-gmail version:- ^6.1

with the above package and configuration, I am trying to send a reply to the email but getting errors as stated below screenshot

Below is the error I am getting 
![image](https://github.com/dacastro4/laravel-gmail/assets/125456979/b3ff00c7-afc2-422f-8c2d-b46d0327dfba)

And below is the screenshot of code.
![image](https://github.com/dacastro4/laravel-gmail/assets/125456979/96b47d4e-fd25-48dd-8af6-10d4b9a404b9)

**Comment by web95-moon** [comment]
i have solved it by taking fork of symfony package and change in source code of symfony package.

**Comment by IbaiEtxebarria** [comment]
I did the same but I was hopping someone had a better solution.

**Comment by glaesser** [comment]
This issue persists even in version 7, not sure why this was closed
