### ISSUE TITLE
getHtmlBody() through an error 

### ISSUE THREAD

**Issue by aqib555** [dacastro4/laravel-gmail#26]
when I use the getHtmlBody() function. error occur when the email has no html in it

**Comment by aqib555** [comment]
I have resolved that issue by making checks on getBody function but i am facing another issue, my token is expire after 60 min, how can i use the refresh token? any help

**Comment by aqib555** [comment]
@dacastro4 or is there anyway to increase the expiration time of gmail-json file save in our storage directory?

**Comment by dacastro4** [comment]
@aqib555 the expiration comes from Gmail, so no, you can't increase it. It should do it automatically.

**Comment by aqib555** [comment]
@dacastro4 Will you please help me, how can i use the refresh token?

**Comment by aqib555** [comment]
@dacastro4 One more thing when i use the getHtmlBody(), it will through and error when email is not in html. Somehow the getBody is going to null

Here is my code: 

if($request->ajax()) {
            $messages = LaravelGmail::message()->take(10)->preload()->all( $pageToken = null );
            foreach ( $messages as $message ) {
                $body[] = $message->getFromEmail();
                $subject[] = $message->getSubject();
                $dataText[] = $message->getHtmlBody(); // Here i am getting an error of getBody() null given
            }
            for($i=0;$i<count($body);$i++)
            {
                if($i == $request->id)
                {
                    $data[0]['from'] = $body[$i];
                    $data[0]['subject'] = $subject[$i];
                    $data[0]['dataText'] = $dataText[$i];
                }
            }
            return response()->json($data);
        }

**Comment by aqib555** [comment]
![capture](https://user-images.githubusercontent.com/42779598/45089167-c06b5a00-b124-11e8-9f80-16bcd7f1fe70.PNG)

**Comment by aqib555** [comment]
One More thing, when my access token is expire it is not getting the refresh token.  Second is when i have two users and i want to integrate both user, it integrate both user with same gmail.json file
