### ISSUE TITLE
Page token missing

### ISSUE THREAD

**Issue by shanwazfarooqe** [dacastro4/laravel-gmail#27]
Page token is missing when using limit data.

LaravelGmail::message()->limit(10)->in( $box = 'inbox' )->preload()->all();

How can i access pagetoken.

**Comment by dacastro4** [comment]
@shanwazfarooqe you know what? Looking at the code I think I totally forgot about that. I'm making a PR right now. Sorry!!!

**Comment by dacastro4** [comment]
@shanwazfarooqe it should be something like:
```
$messages = LaravelGmail::message();
$messages->take(3)->all(); //gets first 3
$messages->next(); //get next 3
```
You can access the token via `$messages->pageToken`

**Comment by dacastro4** [comment]
@shanwazfarooqe please check PR #28

**Comment by shanwazfarooqe** [comment]
I am getting error when using take() method.

Call to undefined method Dacastro4\LaravelGmail\Services\Message::take()

**Comment by dacastro4** [comment]
Hey, @shanwazfarooqe can you send me the code that you're using?

**Comment by shanwazfarooqe** [comment]
Ok
I will send

**Comment by shanwazfarooqe** [comment]
`<?php

namespace App\Http\Controllers;

use Dacastro4\LaravelGmail\Facade\LaravelGmail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class GmailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $access_token;
    protected $url;

    public function __construct()
    {
        $this->middleware('auth');
        if(!LaravelGmail::check())
        {
            return redirect('/oauth/gmail');
        }

        $this->access_token = LaravelGmail::getToken()['access_token'];
        $this->url = "https://www.googleapis.com/gmail/v1/users/me/";
    }

    public function index($pageToken=null)
    {
        if(!LaravelGmail::check())
        {
            return redirect('/oauth/gmail');
        }

        $gmailall = LaravelGmail::message()->in( $box = 'inbox' )->all();
        $inbox = count($gmailall);

        $message_url = $this->url."messages?maxResults=10&q=in:inbox&access_token=".$this->access_token."&pageToken=".$pageToken;
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $message_url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $gmails = json_decode(curl_exec($ch), true);
        $token = $this->access_token;

        return view('email-api',compact('gmails','token','pageToken','inbox'));
    }

    public function trash($id=null)
    {
        $posts =array('id'=>$id);

        $message_url = $this->url."messages/".$id."/trash?access_token=".$this->access_token;
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $message_url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, $posts ? 0 :1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,json_encode($posts));
        $response = json_decode(curl_exec($ch), true);
        if($response){
            return redirect()->route('gmail')->with('status','Email has been deleted');
        } else {
            return redirect()->route('gmail')->with('status','Email could not deleted');
        }
    }

    public function delete($id=null)
    {
        $posts =array('id'=>$id);

        $message_url = $this->url."messages/".$id."?access_token=".$this->access_token;
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $message_url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
        $response = json_decode(curl_exec($ch), true);
        //dd($response);
        if($response){
            return redirect()->route('gmail')->with('status','Email has been deleted');
        } else {
            return redirect()->route('gmail')->with('status','Email could not deleted');
        }
    }

    public function deleteAll(Request $request)
    {
        $ids = $request->ids;

        $queryParams = array(
          'ids' => json_decode($ids)
        );

        $posts = json_encode($queryParams);

        //dd($posts);

        $message_url = $this->url."messages/batchDelete?access_token=".$this->access_token;
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $message_url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, $posts ? 0 :1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,$posts);
        $response = json_decode(curl_exec($ch), true);
        //dd($response);
        if($response){
            return redirect()->route('gmail')->with('status','Email has been deleted');
        } else {
            return redirect()->route('gmail')->with('status','Email could not deleted');
        }
    }

    public function trashAll(Request $request)
    {
        $ids = json_decode($request->ids);
        $response = array();

        foreach($ids as $id):
        $posts =array('id'=>$id);
        $message_url = $this->url."messages/".$id."/trash?access_token=".$this->access_token;
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $message_url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, $posts ? 0 :1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,json_encode($posts));
        $response[] = json_decode(curl_exec($ch), true);
        endforeach;

        if($response){
            return redirect()->route('gmail')->with('status','Email has been deleted');
        } else {
            return redirect()->route('gmail')->with('status','Email could not deleted');
        }
    }

    public function detail($id=null)
    {
        $filtered = LaravelGmail::message()->get($id);
        //dd($filtered);
        return view('email-api-detail',compact('filtered'));
    }

    public function create(Request $request)
    {
        $mail = LaravelGmail::message()->to($request->to)->from(LaravelGmail::user())->subject($request->subject)->message($request->content)->send();
        if($mail)
        {
            return redirect()->route('gmail')->with('status','Email has been sent');
        }
        
    }
}
`

**Comment by dacastro4** [comment]
@shanwazfarooqe you told me that you had an error with `take()`, I don't see the take method implemented in here.

**Comment by shanwazfarooqe** [comment]
take() method works but i still couldnt get page token. So i used it directly to get pageToken().

**Comment by dacastro4** [comment]
> @shanwazfarooqe it should be something like:
> 
> ```
> $messages = LaravelGmail::message();
> $messages->take(3)->all(); //gets first 3
> $messages->next(); //get next 3
> ```
> You can access the token via `$messages->pageToken`

@shanwazfarooqe did you already try what I said in this message?

**Comment by shanwazfarooqe** [comment]
Yes I tried with take method and I couldn't get nextPagetoken for
pagination. So I used it directly and can aceess nextPageToken

**Comment by dacastro4** [comment]
I'm really sorry @shanwazfarooqe, I've been busy. Did you figure it out? if you haven't, let me know so I can keep the issue open and help you.

**Comment by abhiburk** [comment]
I tried using the above mentioned code but i get error 

`Method Illuminate\Support\Collection::next does not exist.`

```
$label =  $request->input("label");
$messages =LaravelGmail::message()
->take(3)
->preload()
->in($label)
->all()
->next();
```

Also I could get token `$messages->pageToken();`

**Comment by bhavdip111** [comment]
> pageToken

Awesome!
