### ISSUE TITLE
I get error "Invalid token format"

### ISSUE THREAD

**Issue by SGarridoDev** [dacastro4/laravel-gmail#29]
First, congrats for you class!

I get an error "Invalid token format". I put the credentials json into storage/app/gmail/tokens/gmail-json.json with this format:

``
{
  "installed": {
    "client_id": "xxxxx",
    "project_id": "xxxxx",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://www.googleapis.com/oauth2/v3/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "xxxxxx",
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "http://localhost"
    ]
  }
}
``

Is possible to use  this package with user service account credentials file?

Thanks in advance.
Regards.

Sergio

**Comment by dacastro4** [comment]
Hey @SGarridoDev, I think the service file has a different structure and no I don't think it works with those files

**Comment by SGarridoDev** [comment]
@dacastro4 That's right, I've worked it out.
