### ISSUE TITLE
Trait method __construct has not been applied, because there are collisions with other trait methods on Dacastro4\LaravelGmail\Services\Message\Mail

### ISSUE THREAD

**Issue by cloudstudio** [dacastro4/laravel-gmail#3]
I get this error when i try to get all emails 

Trait method __construct has not been applied, because there are collisions with other trait methods on Dacastro4\LaravelGmail\Services\Message\Mail

LaravelGmail::message()->all( );

**Comment by dacastro4** [comment]
I pushed the fix for this issue. Let me know @cloudstudio

**Comment by cloudstudio** [comment]
I find other bugs, but all right here :)

Thanks man for you job !

**Comment by dacastro4** [comment]
Just open a new issue and I'll work on it.
