### ISSUE TITLE
Store credentials for multiple users

### ISSUE THREAD

**Issue by jmatembu** [dacastro4/laravel-gmail#35]
I understand that the package is still under development but I just wanted to bring out this issue. At the moment, the credentials file is used to store credentials for only one user. You would have to logout the current user from Gmail so as to get authorization from another user. It would be great to have support for multiple users having their credentials stored in different files (or perhaps same file). This way, when using `LaravelGmail::message()->using($token)->all()` to specify a different token specific to the current user.

Here's a similar scenario I experienced. Let's assume we have two users, User A and User B. User A will have their token stored in the credentials file after they authorize our app with Gmail. Now when we try to get the token with `LaravelGmail::makeToken()` for User B without first logging out User A from Gmail, the `LaravelGmail::check()` method fails and so the token previously stored for User A will be used for User B. So User B ends up retrieving emails of User A.

**Comment by dacastro4** [comment]
@jmatembu Sorry, I've been really busy but I agree with your idea, sounds really good.
I'm going to try to work in your idea soon but feel free to create a pull request if you have a working code.

**Comment by pradeeptry** [comment]
i am getting error
public function message()
    {
        if ( ! $this->getToken() ) {
            throw new AuthException( 'No credentials found.' );
        }
 help me !!!!!!!!!!
![screenshot capture - 2019-01-26 - 22-31-20](https://user-images.githubusercontent.com/30953021/51790375-6003b480-21ba-11e9-9f5c-b1aa5bbd7437.png)

**Comment by dacastro4** [comment]
@pradeeptry that's not related to this issue. Please open a new issue.

**Comment by phppirate** [comment]
Store credentials for multiple users...
I also need this functionality. I could create a PR but it would definitely be a breaking change - If you do not mind this let me know otherwise I will just fork the project

**Comment by dacastro4** [comment]
For breaking changes, we would have to create a new version so we don't break other developer's apps

**Comment by phppirate** [comment]
Right. Are you open to that for just this one feature?

**Comment by SergioAraya** [comment]
yes

**Comment by phppirate** [comment]
Unfortunaltly I will not be able to contribute a PR. I hope this gets added but do not have the time to do it myself.

**Comment by kenanduman1988** [comment]
@dacastro4 please review, PR #59 created.

**Comment by jesephan** [comment]
@dacastro4 kindly review my PR #61 that i submitted that will solve this issue. Thanks

**Comment by dacastro4** [comment]
It's now possible with version `v1.0.0` thanks to @jesephan #61
