### ISSUE TITLE
Whoops.  I figured out where you've configured the directory to store this.

### ISSUE THREAD

**Issue by landes01** [dacastro4/laravel-gmail#36]
For future reference, defaults to storage/app/gmail/tokens

_Originally posted by @rsmith87 in https://github.com/dacastro4/laravel-gmail/issues/13#issuecomment-387690069_

**Comment by landes01** [comment]
how can we generate the gmail / tokens folder in storage / app / gmail / tokens
I use laravel 5.7
I did the update but nothing.

**Comment by dacastro4** [comment]
@landes01  What do you mean with generate? When the user accepts the app permission it should create the file in that path.
