### ISSUE TITLE
Return subject without preload?

### ISSUE THREAD

**Issue by Sokolfx** [dacastro4/laravel-gmail#37]
Hi, there is such a issue.

How to return getSubject() without using preload(), load() ? (loading takes a very looong time with them)

For ex:

Return: $message = LaravelGmail::message()->take(100)->in('inbox')->all();

How to use {{  $message->getSubject() }} Or how to return getheaders() in the main query?

**Comment by dacastro4** [comment]
@Sokolfx  when you try to get the subject it has to load the content and I have to get it first.

In your example your getting a collection of messages so you should loop through the messages and do `{{ $message->getSubject() }}`

**Comment by Sokolfx** [comment]
@dacastro4 But can we take only headers, without preload/load?

I don't understand what you mean. 
After $message = LaravelGmail::message()->take(100)->in('inbox')->all();
I use:
foreach($message as $messages) {
{{ $message->getSubject() }} // but without preload we haven't headers and can't use it
 }

*using with {{ $message->load()->getSubject() }} it's sure longer than preload when takes all messages.

**Comment by dacastro4** [comment]
@Sokolfx this is what you get when you request a list of emails https://developers.google.com/gmail/api/v1/reference/users/messages/list and this when you get the email item https://developers.google.com/gmail/api/v1/reference/users/messages/get#examples.
When you get the list, it doesn't come with headers so I have to load it to get even the title

**Comment by Sokolfx** [comment]
@dacastro4 Ok. I inderstand what you mean. So what the way to return 10-50-100, >100 messages in few seconds? I tried with a couple of options. And with headers it's around 10-12 seconds for 10 messages.
Maybe I do something wrong, or is there another way out to return many messages with getSubject in 1-2 seconds?
Have you encountered a similar problem?

**Comment by Sokolfx** [comment]
Ok, got it. Decided by Batching Request.

**Comment by dacastro4** [comment]
@Sokolfx I haven't encountered a similar problem. The app that I have runs in the background checking for the emails so it doesn't matter. I know it takes a little bit to get the information but that is how the gmail api works ): sorry. Hopefully batching your request at least helps you with the time.
