### ISSUE TITLE
 InvalidArgumentException in Client.php line 433: Invalid token format

### ISSUE THREAD

**Issue by Artanty** [dacastro4/laravel-gmail#39]
Hello! Help me pls!
1) Can't understand how to modify the config file config/gmail.php.
What to do inside of it?
project id,client id,client secret and redirect I set in .env file.
Is it necessary to do something with this string ↓  ?
'credentials_file_name' => env( 'GOOGLE_CREDENTIALS_NAME', 'gmail-json' ),

2) I downloaded .json credentials file from google console, pasted it to: 
"[my project]/storage/app/gmail/tokens" 
then I renamed it to: 'gmail-json.json'
Is it right?

**Comment by Artanty** [comment]
After that I go to index page where I inserted:

<h1>{{ LaravelGmail::user() }}</h1>
                  @if(LaravelGmail::check())
                      <a href="{{ url('oauth/gmail/logout') }}">logout</a>
                  @else
                      <a href="{{ url('oauth/gmail') }}">login</a>
                  @endif

and get "Invalid token format" until I delete this check

**Comment by fajarainul** [comment]
did you found any solution?

**Comment by Artanty** [comment]
no, please help me!

**Comment by pqrs** [comment]
@Artanty, @fajarainul, any news? I'm stuck here too.

**Comment by Artanty** [comment]
No, i tried another library and wrapper for connect to gmail via api, but nothing.
Although gCalendar api and socialite with Google auth work fine.

**Comment by dacastro4** [comment]
I'm really glad to hear that @Artanty

**Comment by Artanty** [comment]
> I am stuck too. I already did exactly what you did. Set values in .env, download json file provided by Google console and also put it into storage/app/gmail/tokens. One thing I know is we must provide access_token, refresh_token, and expires_in inside credentials.json, but I dont know the proper way to afford this.

We don't need to download .json file and put it into  storage/app/gmail/tokens.
This file is creating automatically on callback function "LaravelGmail::makeToken();"
delete it if you put it into storage/app/gmail/tokens.

**Comment by pqrs** [comment]
Thanks @dacastro4 but I must be doing something wrong. I don't know if it is in the config or in the Google console. Is there any step by step tutorial or any working example somewhere I can look at?

**Comment by dacastro4** [comment]
@pqrs what kind of error are you getting?

**Comment by pqrs** [comment]
No credentials found.

**Comment by pqrs** [comment]
Solved! It works now... nothing like restart from the beginning! :)

**Comment by iqroyan** [comment]
> Hey guys I have an example of my gmail-json.json
> 
> ```
> {
>   "access_token": "ACCESS",
>   "token_type": "Bearer",
>   "expires_in": 3600,
>   "refresh_token": "REFRESH",
>   "created": 1522885414,
>   "email": "EMAIL"
> }
> ```
> 
> My `.env`
> 
> ```
> GOOGLE_PROJECT_ID=PROJECT_ID
> GOOGLE_CLIENT_ID=ID.apps.googleusercontent.com
> GOOGLE_CLIENT_SECRET=SECRET
> GOOGLE_REDIRECT_URI=/oauth/gmail/callback
> ```
> 
> Hope it helps.

hey Danial access_token same of GOOGLE_CLIENT_ID?
