### ISSUE TITLE
i haves a error in email sending in laravel 

### ISSUE THREAD

**Issue by usamasarfraz143** [dacastro4/laravel-gmail#40]
$mail = new Mail();
$mail->to($data['to'])->from('us****@piecyfer.com')->subject('text')->message('this is trhe testing email')->send(); 

when i use to this code i wall received this kindly guide me about how to send email ;
Call to undefined method Illuminate\Support\Facades\Mail::to() (View: C:\xampp\htdocs\mygoogleapi\resources\views\welcome.blade.php)

**Comment by dacastro4** [comment]
@usamasarfraz143 did you figure it out?

**Comment by usamasarfraz143** [comment]
yes yes
