### ISSUE TITLE
Class laravelgmail does not exist

### ISSUE THREAD

**Issue by pappleweb** [dacastro4/laravel-gmail#41]
Hi,

I want to configure your LaravelGmail, but I have this message on my Laravel 5.4.36 : "Class laravelgmail does not exist"

I use PHP 7.1 and your LaravelGmail in 0.4 and 0.6, the problem is the same.

I have been in my config/app.php : 
       ` Dacastro4\LaravelGmail\LaravelGmailServiceProvider::class,` (provider)
       `'LaravelGmail' => Dacastro4\LaravelGmail\Facade\LaravelGmail::class,`(aliases)

What is the problem ?

**Comment by dacastro4** [comment]
Hey @pappleweb,

I just tried adding `"dacastro4/laravel-gmail": "^0.6"` to a new Laravel project and copied and pasted it what you sent me and it works fine.

I put this on the web.php and it worked fine.
```
use Dacastro4\LaravelGmail\Facade\LaravelGmail;

Route::get( '/', function () {
	LaravelGmail::getAuthUrl();
    return view('welcome');
});
```

**Comment by pappleweb** [comment]
Hi !
Thanks you, On my second computer, the module works. I think that the problem is in the configuration app on my first computer.

Else, I have a new question, I post it on a new issue :).
Thanks you.

**Comment by dacastro4** [comment]
Awesome. I'm going to close this one.
