### ISSUE TITLE
Get whole thread.

### ISSUE THREAD

**Issue by dmitrymalys** [dacastro4/laravel-gmail#45]
Hello, is there a way to get the whole thread, by thread id?

**Comment by dacastro4** [comment]
@dmitrymalys is that a filter on gmail?

**Comment by xqsit** [comment]
Yes I want to fetch all messages using thread id. Please refer this
https://developers.google.com/gmail/api/v1/reference/users/threads/get

**Comment by IbaiEtxebarria** [comment]
any updates?
