### ISSUE TITLE
How Do I use Attachment Class ?

### ISSUE THREAD

**Issue by abhiburk** [dacastro4/laravel-gmail#47]
Hey I am implementing Gmail using your package but their is not much info added in this pack document. So at this point I am stuch on Attachment class it would be great if you add more info about how to use that class as I want to download attachment of an email.

**Comment by jmatembu** [comment]
@abhiburk 

The documentation shows you the methods you need to get attachments from an email. Here is some code example assuming you have already retrieved your emails and looping from each to get attachments.

```
if ($email->hasAttachments()) {
    // Email has attachments
    $attachments = $email->getAttachments()->map(function ($attachment) {
        // Save each attachment to your preferred location
        return $attachment->saveAttachmentTo('path/to/downloaded/attachments', filename, 'disk');
    });

    // You now have the paths to the downloaded files in the $attachments variable.
}
```

The methods availed to you by the package that I have used in the code above are: `hasAttachments()`, `getAttachments()`, `saveAttachmentTo($path, $filename, $disk)`

**Comment by abhiburk** [comment]
Okay the one which you share is extremely easy and I gonna replace it with mine one. How I did was
```
$message = LaravelGmail::message()->get( $gmailID );
        $parts=($message->payload->parts);
        foreach ( $parts as $part ) {
			$body = $part->getBody();
			if ( $body->getAttachmentId() ) {
				$attachment = ( new Attachment( $gmailID, $part ) );
                $attach['attachment'][] = ['fileName'=>$attachment->getFileName(),
                'size'=> $attachment->getSize(),
                'data'=>$attachment->getData()];
			}
        }
```

My Bad :-P

By the way thank you this package is very helpful.

**Comment by dacastro4** [comment]
@jmatembu thanks for the help!
@abhiburk I'm glad that you find it helpful.

**Comment by abhiburk** [comment]
Yes it helped me.
Also I wanted to let you know you can add search function in Message class as their is only in: option available in it. I added it in my code. Hope this helps you.
