### ISSUE TITLE
How get id after send email?

### ISSUE THREAD

**Issue by sahakavatar** [dacastro4/laravel-gmail#48]
Hey @dacastro4 .
How can I get email id after send email
$mail =new Mail()->to($data['to'])->from('someting@foo.com')->subject($subject)->message($texteditor)->send();
$mail->getId() return null
https://www.screencast.com/t/NqH6xpZC

**Comment by dacastro4** [comment]
@sahakavatar let me check this out

**Comment by dacastro4** [comment]
Sorry @sahakavatar I've been busy. I was returning a new message instance of adding the properties to the existing Mail instance.

**Comment by dacastro4** [comment]
Solved in #57

**Comment by sahakavatar** [comment]
thanks :)
