### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by JexPY** [dacastro4/laravel-gmail#5]
![image](https://user-images.githubusercontent.com/9080830/37463055-795be2aa-286d-11e8-8f5c-1e2803dc73ce.png)

**Comment by dacastro4** [comment]
@JexPY this is when you run what?

**Comment by JexPY** [comment]
@dacastro4  For example 

```
LaravelGmail::message()
        ->from('myusers@gmail.com')
        ->in('TRASH')
        ->all()
```

**Comment by dacastro4** [comment]
Thanks, @JexPY. I'll check this tonight.

**Comment by dacastro4** [comment]
Hey @JexPY, which version of the package are you using? I'm testing and I cannot replicate the same exception.

**Comment by JexPY** [comment]
@dacastro4 
![image](https://user-images.githubusercontent.com/9080830/37510425-6ec02f5c-2914-11e8-89ab-ac484fe241ad.png)

And as soon as I comment this part
class Mail extends GmailConnection

> {
>     use HasDecodableBody,
>         HasHeaders,
>         Modifiable;
>     //     Replyable {
>     //     Replyable::__construct as private __rConstruct;
>     //     Modifiable::__construct as private __mConstruct;
>     // }
It runs

**Comment by dacastro4** [comment]
I'm trying to replicate the issue. What version of PHP are you using?

**Comment by dacastro4** [comment]
@JexPY I pushed some new code. Let me know if it fixes your issue.

**Comment by JexPY** [comment]
@dacastro4 It's fixed. Good Luck
