### ISSUE TITLE
error "Metadata scope does not support 'q' parameter"

### ISSUE THREAD

**Issue by drolean** [dacastro4/laravel-gmail#50]
on this line
`$messages = LaravelGmail::message()->unread()->preload()->all()->take(50);`

`{ "error": { "errors": [ { "domain": "global", "reason": "forbidden", "message": "Metadata scope does not support 'q' parameter" } ], "code": 403, "message": "Metadata scope does not support 'q' parameter" } }`

**Comment by dacastro4** [comment]
Hey @drolean. What do you have in the gmail config file?

**Comment by drolean** [comment]
```
 'project_id'    => env('GOOGLE_PROJECT_ID'),
    'client_id'     => env('GOOGLE_CLIENT_ID'),
    'client_secret' => env('GOOGLE_CLIENT_SECRET'),
    'redirect_url'  => env('GOOGLE_REDIRECT_URI', '/'),

    'scopes' => [
        'all',
        'readonly',
        'modify',
        'metadata',
    ],

    'access_type' => 'offline',

    'approval_prompt' => 'force',

    'credentials_file_name' => env('GOOGLE_CREDENTIALS_NAME', 'gmail-json'),
```

**Comment by dacastro4** [comment]
Did you use `setAdditionalScopes` to set any additional scopes?

**Comment by dacastro4** [comment]
Oh, I'm sorry. It says it right there.
Remove 'metadata' scope and it should work.

**Comment by drolean** [comment]
tnks for the quick help.
