### ISSUE TITLE
Filter e-mails by date 

### ISSUE THREAD

**Issue by gmarciano** [dacastro4/laravel-gmail#51]
Hey, how are you?

Is there a way to filter the e-mails by date like gmail allows you to? (after:, before:, older_than:, etc.).
I had a quick look at your code and I didn't saw it.

**Comment by gmarciano** [comment]
Actually, what do you think about adding a pure gmail query function, like:
```php
public function raw($query)
{
    $this->add($query);

    return $this;
}
```
And the usage would be like:
```php
LaravelGmail::message()->raw('after:2018-12-30 from:mycoolemail@some.com subject:LaravelGmail');
```
<br>
I think you already had thought about doing something like that and it didn't work, that's why I ask. But anyway, hope you like the idea! :smile: 

###### I'm up to do the changes, just want the background about the changes so that I don't make a rework that may not be effective

**Comment by gmarciano** [comment]
See if you think these are relevantes changes

```php
/**
 * Filter to get only emails after a specific date
 *
 * @param $date
 *
 * @return $this
 */
public function after( $date )
{
	$this->add( "after:{$date}" );

	return $this;
}

/**
 * Filter to get only emails before a specific date
 *
 * @param $date
 *
 * @return $this
 */
public function before( $date )
{
	$this->add( "before:{$date}" );

	return $this;
}

/**
 * Filter by a Gmail raw query
 * Label should be the last thing to put in the raw query
 * 
 * @param $query
 * 
 * @return $this
 */
public function raw($query)
{
	$this->add( $query );

	return $this;
}

**Comment by dacastro4** [comment]
@gmarciano amazing idea. Adding it now. (Sorry for the late response)
