### ISSUE TITLE
How to set state variable

### ISSUE THREAD

**Issue by stacybot123** [dacastro4/laravel-gmail#53]
Hi,

How do I set state variable on client.

**Comment by dacastro4** [comment]
@stacybot123 can you elaborate more please

**Comment by stacybot123** [comment]
The state variable can be used to send a custom value with with the OAuth request. For example : if every user on the app have their custom subdomain (wildcard subdomain) it is impossible to add each of them on the google app, or to disable cross site forgery. So google can pass the state with the request and identify the user and redirect back to the correct resource. 
If I use the google client directly it can be used as below:

```
            $client = new Google_Client();
            $client->setClientId('XXXXXXXXXXXX');
            $client->setClientSecret('XXXXXXXXXXXXX');
            $client->setAccessType('offline'); 
            $client->addScope(Google_Service_Gmail::GMAIL_SEND);
            $client->setRedirectUri('https://app.example.com/oauth2callback');
            $client->setState('mycustom_value');
            $client->setIncludeGrantedScopes(true);
            $auth_url = $client->createAuthUrl();
            header('Location: ' . filter_var($auth_url, FILTER_SANITIZE_URL));

```
The data it will receive after the OAuth validation on server will look like this:

```
array (
  'state' => 'mycustom_value',
  'code' => 'XXXXXXXXXXXXXXXXXXX',
  'scope' => 'https://www.googleapis.com/auth/gmail.send',
)  
```
[Here is the doc on google](https://developers.google.com/identity/protocols/OAuth2WebServer) which have the info

**Comment by dacastro4** [comment]
@stacybot123 I check the code and I don't have the state as a variable that can be set.
