### ISSUE TITLE
Mail Fetching is too slow. How can I solve it?

### ISSUE THREAD

**Issue by shashankj99** [dacastro4/laravel-gmail#58]

**Comment by dacastro4** [comment]
@shashankj99 Google SDK doesn't provide a way to do this faster, I made the function mostly to use on a background process. Sorry

**Comment by shashankj99** [comment]
Thank you for your response sir but i managed to do it with javaScript

**Comment by dacastro4** [comment]
@shashankj99 Did you find a method to get them in a batch request?

**Comment by shashankj99** [comment]
yes

**Comment by shashankj99** [comment]
- put it in any directory
- then serve locally
     eg:- php -S localhost:5000 or  python -m SimpleHTTPServer 5000(python
2x) & python -m http.server 5000(python 3x)

**Comment by abhiburk** [comment]
@shashankj99  can please explain a bit or any sort of code you wrote to fetch emails faster.

**Comment by dacastro4** [comment]
@abhiburk I didn't use any of that code

**Comment by abhiburk** [comment]
Can you check #60 ?
