### ISSUE TITLE
Good documentation - do you have a tutorial?

### ISSUE THREAD

**Issue by sbasi5576** [dacastro4/laravel-gmail#6]
Hi,

Do you have a step by step tutorial?

I am assuming one will have to put use LaravelGmail; in their controller?

Thanks

**Comment by dacastro4** [comment]
Hey @sbasi5576. I don't have a step by step tutorial but I'll help you with everything you need.

**Comment by sbasi5576** [comment]
Thanks.  Do I need laravel 5.6 or can I use it with 5.1?  I tried installing it on 5.1 and got some swiftmailer related errors.

**Comment by sbasi5576** [comment]
Also do I need to declare it in my controller?

**Comment by dacastro4** [comment]
@sbasi5576. Can you send me the errors on 5.1?.
Yes, you need to declare `use Dacastro4\LaravelGmail` on your controller.

**Comment by sbasi5576** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dacastro4/laravel-gmail ^0.3.6 -> satisfiable by dacastro4/laravel-gmail[v0.3.6].
    - Conclusion: remove swiftmailer/swiftmailer v5.4.9
    - Conclusion: don't install swiftmailer/swiftmailer v5.4.9
    - dacastro4/laravel-gmail v0.3.6 requires swiftmailer/swiftmailer ^6.0 -> satisfiable by swiftmailer/swiftmailer[v6.0.0, v6.0.1, v6.0.2].
    - Can only install one of: swiftmailer/swiftmailer[v6.0.0, v5.4.9].
    - Can only install one of: swiftmailer/swiftmailer[v6.0.1, v5.4.9].
    - Can only install one of: swiftmailer/swiftmailer[v6.0.2, v5.4.9].
    - Installation request for swiftmailer/swiftmailer (locked at v5.4.9) -> satisfiable by swiftmailer/swiftmailer[v5.4.9].

**Comment by dacastro4** [comment]
Perfect. I'm gonna get into this tomorrow :). Thank you. If you need more help let me know

**Comment by sbasi5576** [comment]
I upgraded to 5.6 was able to install it.  Thanks.  I will try it out in the morning.

**Comment by sbasi5576** [comment]
I looked at it further - I think it would be helpful if you can provide a sample controller or a starter function in the tutorial to cover the following.

LaravelGmail::getAuthUrl Gets the URL to auth the user.

LaravelGmail::redirect You can use this as a direct method <a href="{{ LaravelGmail::redirect() }}">Login</a>

LaravelGmail::logout Logs out the user

LaravelGmail::check Checks if the user is logged in
