### ISSUE TITLE
Batch Request ?

### ISSUE THREAD

**Issue by abhiburk** [dacastro4/laravel-gmail#60]
Using this package I am able to do What I want but while fetching gmail messages it takes lot of time to get those emails so I found out that we get message id and then using this id we have to get particular message. The reason I understood is we are making multiple call for every email and thats the reason getting emails takes lot of time. Now how do I do it using Batch Request ?

**Comment by dacastro4** [comment]
@abhiburk Check google documentation to see if they have a batch request, I'm not sure

**Comment by dacastro4** [comment]
@abhiburk https://developers.google.com/gmail/api/guides/batch they are deprecating this feature :(

**Comment by abhiburk** [comment]
What is the alternative for this then ?

**Comment by dacastro4** [comment]
fixed in #87

**Comment by abhiburk** [comment]
I did composer update but the batchRequest isn't reflected in my package

**Comment by abhiburk** [comment]
Also can you tell me how do I use batchRequest function ?

**Comment by dacastro4** [comment]
You changed it to 2.0 and it didn't work?

**Comment by abhiburk** [comment]
Yes I changed it with 2.0 and did composer update but am not able to see batchRequest in Message.php while it was in your repo commit

**Comment by dacastro4** [comment]
And do you have 2.0 or ~2.0? I don't remember if I had to push a 2.0.1

**Comment by abhiburk** [comment]
2.0

**Comment by dacastro4** [comment]
Try changing it to ~2.0 to see if it works. I'm not currently infront of a
computer that's why I'm trying to guess the solution

**Comment by abhiburk** [comment]
Okay and I think I also tried v2.0 in .json

**Comment by abhiburk** [comment]
this is what in my composer "dacastro4/laravel-gmail": "~2.0", and when did composer update I get "Nothing to install or update"

**Comment by dacastro4** [comment]
I'm finally in front of a computer and I tried and it failed. I push a 2.0.1 version and changed my composer.json to "~2.0" and I worked.

**Comment by abhiburk** [comment]
Ok so what i suppose to do now ?

**Comment by dacastro4** [comment]
Run `composer update`

**Comment by abhiburk** [comment]
Okay I will and can you tell me how do I use the batchRequest to get emails within sec as it taks lot of tike to load gmail inbox now it takes 15 to 20 seconds

**Comment by abhiburk** [comment]
Hey still I am unable to load email faster it takes very much time to fetch into my inbox ?
