### ISSUE TITLE
Problem with Login Multiple Users Name

### ISSUE THREAD

**Issue by nasatome** [dacastro4/laravel-gmail#68]
Probably this related to #67

![error1-laravel-gmail-2019-04-30_13-17](https://user-images.githubusercontent.com/18271791/56984232-2b9dec80-6b4b-11e9-84a5-a267104684ea.png)
![error2-laravel-gmail-2019-04-30_13-17](https://user-images.githubusercontent.com/18271791/56984233-2b9dec80-6b4b-11e9-8fc6-a6054bc5662e.png)
![error3-laravel-gmail-2019-04-30_13-17](https://user-images.githubusercontent.com/18271791/56984234-2b9dec80-6b4b-11e9-92c7-81a8686e9164.png)

There is a problem when creating multiple users, call the sprintf function again at a time that should not be called, since the function getFileName already calls it before.

In a moment more I will do a PullRequest to correct this dilemma, I hope you accept it, I just realized a few minutes ago, and I will use your project to take it to production soon.

**Comment by nasatome** [comment]
Ready, I made a commit, I'm going to try it ... and in a moment I report results.

**Comment by dacastro4** [comment]
@nasatome wow.. makes total sense. How did I miss that? Thank you so much.

So basically we need to replace
```php
if ($userId && $allowMultipleCredentials) {
	$file = sprintf('gmail/tokens/%s-%s.json', $fileName, $userId);
} else {
	$file = "gmail/tokens/$fileName.json";
}
```
for 
```php
$file = "gmail/tokens/$fileName.json";
```
Because we are handling the name and multi credentials thing inside `getFileName`

**Comment by nasatome** [comment]
It's correct ... let's test it ... and I'll make you a PR
To take care of the quality of this excellent piece of software that you have made.

**Comment by dacastro4** [comment]
@nasatome Sorry and thank you for that, I really appreciate it.

**Comment by nasatome** [comment]
ups, I included all the previous PRs thinking that they were already in master, could you do merge to master?
