### ISSUE TITLE
Does anyone have have a sample controller?

### ISSUE THREAD

**Issue by sbasi5576** [dacastro4/laravel-gmail#7]
I am looking for an example to get started.  Especially how to use the following:

LaravelGmail::getAuthUrl Gets the URL to auth the user.

LaravelGmail::redirect You can use this as a direct method <a href="{{ LaravelGmail::redirect() }}">Login</a>

LaravelGmail::logout Logs out the user

LaravelGmail::check Checks if the user is logged in

**Comment by dacastro4** [comment]
I'm sorry, I've been a bit busy. Do you still need the examples? I can show a code that I have that might help you.

**Comment by dacastro4** [comment]
I'll show you some examples that I have in my local.

## Welcome Blade:
```blade
<body>
    <h1>{{ LaravelGmail::user() }}</h1>
    @if(LaravelGmail::check())
        <a href="{{ url('oauth/gmail/logout') }}">logout</a>
    @else
        <a href="{{ url('oauth/gmail') }}">login</a>
    @endif
</body>
```

## Routes:
```php
Route::get('/oauth/gmail', function (){
    return LaravelGmail::redirect();
});

Route::get('/oauth/gmail/callback', function (){
    LaravelGmail::makeToken();
    return redirect()->to('/');
});

Route::get('/oauth/gmail/logout', function (){
    LaravelGmail::logout(); //It returns example if fails
    return redirect()->to('/');
});
```

Then if in your controller or wherever you want to do your logic, you do something link:
```php
$messages = LaravelGmail::message()->subject('test')->unread()->preload()->all();
foreach ( $messages as $message ) {
    $body = $message->getHtmlBody();
    $subject = $message->getSubject();
}
```
Note that if you don't preload the messages you have to do something like:
` $body = $message->load()->getSubject();`
and after that you don't have to call it again.
