### ISSUE TITLE
[Question] What settings of Code Fixer/Style do you use?

### ISSUE THREAD

**Issue by nasatome** [dacastro4/laravel-gmail#70]
I use PHPStorm in my project, but I see that we have different code style settings, so I have not indented the code

For example, normally in laravel projects I do not use tabs, I replace them with spaces, but the readme.md has tabs

![Screenshot from 2019-04-30 16-17-24](https://user-images.githubusercontent.com/18271791/56994208-0a95c580-6b64-11e9-8cda-db9287ff65e8.png)

I think I'll be uploading corrections to the project (if necessary for mine), so this is a good question to ask you.

PSR1/PSR2 Style?...
Tabs? Spaces?
Laravel Style?

We do not worry about that and in the future we apply https://styleci.io/? 
https://laravel.com/docs/5.8/contributions#coding-style
https://www.php-fig.org/psr/psr-2/

``` 
2.4. Indenting

Code MUST use an indent of 4 spaces, and MUST NOT use tabs for indenting.
```
This to not make you run fixers to the code with which it collaborates. and save yourself some time

PD: I appreciate that you have helped me with the previous PR

**Comment by dacastro4** [comment]
@nasatome I use my default configuration for all my project but you're right about something, this is an open source project and I should use something more standard so people can easily make PR's without any problems. I might change this project to be that preset styles from your SS, the Laravel one. Thank you so all this information and links
