### ISSUE TITLE
If my token expired, it does not refresh automatically

### ISSUE THREAD

**Issue by nasatome** [dacastro4/laravel-gmail#71]
Probably related #15 

The token never refreshes, apparently in the file
src/GmailConnection.php#38
The "if"  never enter.

I will see how I can solve it.

**Comment by nasatome** [comment]
at "__construct" line#38 the function "check"
on line 88 send a call to "isAccessTokenExpired"
that sends to call the "parent" that returns:
```
@return bool Returns True if the access_token is expired.
```
the function "refreshTokenIfNeeded" The first thing he calls to call is:  "isAccessTokenExpired"

therefore the constructor's action is redundant

I'll try this theory and if I'm right, I'll send you a PR

**Comment by dacastro4** [comment]
Sorry for the delay @nasatome and thanks for taking care of this issue. What seems weird is that I have an app in production using this and I have never had this problem (token not refreshing). Let me know how I can help

**Comment by nasatome** [comment]
then most likely in the current version 1.0.5 under certain conditions that refresh may not be working.

Are you using multiple users in that production application?

**Comment by nasatome** [comment]
https://github.com/nasatome/laravel-gmail/commit/743ed9348ea42551db8cb2a9aa8a00583b3416be
It allows you to do things like:
```
$token = LaravelGmail::makeToken();
return view('googleLoginCallback', ['email' => $token['email'] ?? 'ERROR']);
```

**Comment by nasatome** [comment]
by the way, the reason you notice why this happened is because: 
https://developers.google.com/identity/protocols/OAuth2#expiration

```

- The user account has exceeded a maximum number of granted (live) refresh tokens.

There is currently a limit of 50 refresh tokens per user account per client. If the limit is reached, creating a new refresh token automatically invalidates the oldest refresh token without warning. This limit does not apply to service accounts.

There is also a larger limit on the total number of refresh tokens a user account or service account can have across all clients. Most normal users won't exceed this limit but a developer's test account might.

```


this leads me to the conclusion that as I am asking (live) too many tokens I exceed the maximum allowed by google, apparently 50, When I send an email, the credentials are also sent,  I guess that's a live token.


```
//vendor/google/apiclient/src/Google/Client.php#367

 // add refresh subscriber to request a new token
      if (isset($token['refresh_token']) && $this->isAccessTokenExpired()) {
        $credentials = $this->createUserRefreshCredentials(
            $scopes,
            $token['refresh_token']
        );
      }
    }

    $authHandler = $this->getAuthHandler();

    if ($credentials) {
      $callback = $this->config['token_callback'];
      $http = $authHandler->attachCredentials($http, $credentials, $callback); //<--- Here
    } elseif ($token) {
```

I just tried version 1.0.5 and tokens refreshing now works, in the new pullRequest, I already save the tokens so it's a way to avoid the excess of refresh tokens granted 
(I guess this only happens to the developers ... but it will be good to add it, so that it does not happen to other developers, that's why you in production did not happen to you @dacastro4 )
