### ISSUE TITLE
when I grant permissions , it does not logged me in

### ISSUE THREAD

**Issue by Luqman6666** [dacastro4/laravel-gmail#73]
I have created same template as you described, when I click on login , gmail asks me to allow permissions, after I grant all permissions, it redirects me to an invalid url and does not log me in.

**Comment by dacastro4** [comment]
You should be able to change the redirect URL from the Google Console and
check that matches with one of your routes

**Comment by nasatome** [comment]
In Google Console: Client ID for Web application

```
Authorized JavaScript origins : https://yourdomain.com
Authorized redirect URIs : https://yourdomain.com/oauth/gmail/callback
```

.env:
`GOOGLE_REDIRECT_URI=https://yourdomain.com/oauth/gmail/callback`


web.php // routes file
```
Route::get('/oauth/gmail/callback', function (){
    LaravelGmail::makeToken();
    return redirect()->to('/');
});
```

then:

```
php artisan clear-compiled
php artisan config:clear
php artisan cache:clear
php artisan route:clear
php artisan view:clear
```
@Luqman6666

**Comment by dacastro4** [comment]
Are you doing this locally?

**Comment by Luqman6666** [comment]
Yes,  I am doing on Local host.  Is it possible on Local host? Can someone
describes all the steps to access my unread emails  using this package  ?

**Comment by Luqman6666** [comment]
> Are you doing this locally?

yes, doing on Local host. Dacastro, please provide a few step explanation so that I can resolve my problem.  It would be great if you can provide clear example for each step required to fetch my emails in My Laravel app

**Comment by nasatome** [comment]
@Luqman6666  check out https://ngrok.com/

**Comment by Luqman6666** [comment]
> In Google Console: Client ID for Web application
> 
> ```
> Authorized JavaScript origins : https://yourdomain.com
> Authorized redirect URIs : https://yourdomain.com/oauth/gmail/callback
> ```
> 
> .env:
> `GOOGLE_REDIRECT_URI=https://yourdomain.com/oauth/gmail/callback`
> 
> web.php // routes file
> 
> ```
> Route::get('/oauth/gmail/callback', function (){
>     LaravelGmail::makeToken();
>     return redirect()->to('/');
> });
> ```
> 
> then:
> 
> ```
> php artisan clear-compiled
> php artisan config:clear
> php artisan cache:clear
> php artisan route:clear
> php artisan view:clear
> ```
> 
> @nasatome   can I do it on Local host, can you explain all steps required to fetch email on Local host..I use php artisan serve, my local host runs at localhost:8000...
1: when I call localhost:8000/oauth/gmail , gmail asks me to select your account, I select one gmail account. then it asks for permission , I grant all permissions, when I grant permission , it redirects me to 
the following URL
http://localhost:8000/urn:ietf:wg:oauth:2.0:oob,http://localhost:8000?code=4/SgGzKjA__cOaOKvesCdJRJHFE4fzg238vk-3kQCIglXou9RTGsxoJk0WHxMJz-yQOfXgvLFnOIhnb72EbTePpOc&scope=https://www.googleapis.com/auth/gmail.readonly%20https://www.googleapis.com/auth/gmail.modify%20https://www.googleapis.com/auth/gmail.metadata.
my routes in web.php are as follows
Route::get('/oauth/gmail/callback', function (){
    LaravelGmail::makeToken();
    return redirect()->to('/');
});

Route::get('/oauth/gmail/logout', function (){
    LaravelGmail::logout(); //It returns exception if fails
    return redirect()->to('/');
});
Route::get('fetch_emails',function(){
 
    $messages = LaravelGmail::message()->subject('test')->unread()->preload()->all();
    dd($messages);
});
and redirect url in .env is as follows
GOOGLE_REDIRECT_URI=urn:ietf:wg:oauth:2.0:oob,http://localhost:8000      
                @dacastro4 
please guide me in simple words

**Comment by Luqman6666** [comment]
@dacastro4    Issue has been resolved on Live server. I had to define correct url's in Google console and redirect_urls.
