### ISSUE TITLE
Manual input of json file name

### ISSUE THREAD

**Issue by igorhmelevskoy** [dacastro4/laravel-gmail#74]
Great solution, thanks.
Is it possible to somehow transfer the name of the json file when calling LaravelGmail :: without recourse to authorization?
To be able to work with several confirmed accounts simultaneously, from one laravel account.

**Comment by nasatome** [comment]
I think the ideal thing would be to save the file with the name of the email

**Comment by igorhmelevskoy** [comment]
> I think the ideal thing would be to save the file with the name of the email

Yes, I thought this way. But the user can have 3 mails for example and he can switch in it without leaving the Laravel. And depending on which one he chooses, you need to select this json file, but I cannot figure out how to transfer the meningor so that the function selects the name transferred to it from outside and then it works with the token from the file.

**Comment by nasatome** [comment]
It's just an idea in the air ...
I still can not find the solution to remove the Laravel account ID, but it occurs to me, save the Laravel ID, concatenated the person's email to the name, and then send the email through a function that reads the json file for example `setEmail($email)`, and then use `setToken($token)`
```
	private function getFileName()
	{
               
		$userId = auth()->id();
		$credentialFilename = $this->_config['gmail.credentials_file_name'];
		$allowMultipleCredentials = $this->_config['gmail.allow_multiple_credentials'];
		if ($userId && $allowMultipleCredentials) {
			return sprintf('%s-%s-%s', $credentialFilename, $userId, $this->emailAddress);
		}
		return $credentialFilename;
	}
```
but I can not get it mentally functional

**Comment by igorhmelevskoy** [comment]
I tend to, to specify the file name (for example, user email) when you first call the shell, for example
`$gmailSt = new LaravelGmail ('mail@gmail.com.json');`
and then continue to work with `$gmailSt`

**Comment by nasatome** [comment]
I'm interested in implementing what you mention, this is just a personal note: so that later I can receive other initialization values ​​in addition to the email.

$gmailSt = new LaravelGmail (['email' => 'mail@gmail.com.json']);

**Comment by igorhmelevskoy** [comment]
Redid a little and everything works as I wanted)
I fix that changed, it is possible to be useful for the subsequent implementation and improvement of the module.
file: /vendor/dacastro4/laravel-gmail/src/Services/Message/Mail.php
![1557827806329](https://user-images.githubusercontent.com/19838481/58017466-f9a7f680-7b08-11e9-9b09-ab509f6358bc.png)
file: /vendor/dacastro4/laravel-gmail/src/GmailConnection.php
![1557990264494](https://user-images.githubusercontent.com/19838481/58017560-31af3980-7b09-11e9-9285-599b25095110.png)
![1558350757096](https://user-images.githubusercontent.com/19838481/58017624-573c4300-7b09-11e9-97f1-a9a598e4f375.png)
file: /vendor/dacastro4/laravel-gmail/src/Traits/Configurable.php
![1558350838968](https://user-images.githubusercontent.com/19838481/58017697-88b50e80-7b09-11e9-8026-8586041d8c35.png)
We receive a token and save it in a file under the name of the mail.
![1558351131621](https://user-images.githubusercontent.com/19838481/58017962-37594f00-7b0a-11e9-979a-6a5e3c87a25a.png)
And then we choose from which file we take the token.
`$mail = new Mail('filenamejson@gmail.com');`
`$mail->to( "test@gmail.com", "Test Name");`
 `$mail->subject( "Test" );`
`$mail->message( "my test message" );`
`$mail->send();`
Thanks for the great module, success in further improvement!
And I apologize for my English, I am from Ukraine =)
@nasatome 
@dacastro4

**Comment by igorhmelevskoy** [comment]
Во всем разобрался )

**Comment by dacastro4** [comment]
@igorhmelevskoy sorry for the delay but it looks like a good idea.
@nasatome thank you for the help

**Comment by adrianbarnes** [comment]
@dacastro would you be adding this anytime soon to the package?
