### ISSUE TITLE
sometimes data is in payload->body->data and part doesn't exist.

### ISSUE THREAD

**Issue by martinschenk** [dacastro4/laravel-gmail#75]
Sometimes data (the email text)  is in payload->body->data and part doesn't exist. 
In this case when calling $message->getHtmlBody() it is empty, because i think Mail.php is expecting data to be always in payload->parts[]->body->data 

So if i add to Mail.php in function getBody on line 383

    }elseif($this->payload->body->data){
        return $this->payload->body->data;
    }

it works.
May be i understood wrong... please tell me.
PS: laravel-gmail is great! Congratulations.

**Comment by dacastro4** [comment]
thanks @martinschenk 

Can you tell me what kind of email are you sending? It doesn't have parts it only has a body, that's what you are saying?

**Comment by martinschenk** [comment]
Sorry @dacastro4 , i didn't explain me well. I will try to explain me better:

I am not sending. I am am receiving with:
    $message = LaravelGmail::message()->get( $mailId );
Your code expects to be the body of the message always in 
    payload->parts[]->body->data
but sometimes, there are emails, which have the body in
    payload->body->data

Here is an example in the screenshot:
![Bildschirmfoto 2019-05-24 um 12 30 10](https://user-images.githubusercontent.com/635827/58322196-94ae1280-7e20-11e9-83d8-a96e6dba307b.png)

Its a email from Uber Eats. 

The code i offered, is to cover this case in Mail.php in function getBody on line 383
        }elseif($this->payload->body->data){
            return $this->payload->body->data;
        }
ans parts do not exist.

**Comment by dacastro4** [comment]
@martinschenk got it. Yeah, I think adding that would hurt anything and it will make your case work just fine

**Comment by martinschenk** [comment]
@dacastro4 tried to make pull request #82 
Sorry, for the mess, its my first pull request ever.

**Comment by dacastro4** [comment]
@martinschenk no worries, thank you
