### ISSUE TITLE
Gmail returning null Values for email related fields      

### ISSUE THREAD

**Issue by Luqman6666** [dacastro4/laravel-gmail#76]
$messages = LaravelGmail::message()->take(1)->all( $pageToken = null );
dd($messages);
in requested scopes, it is returning follwing three:
 #requestedScopes: array:3 [▼
        0 => "https://www.googleapis.com/auth/gmail.readonly"
        1 => "https://www.googleapis.com/auth/gmail.modify"
        2 => "https://www.googleapis.com/auth/gmail.metadata"
      ]
it is returning null values for email related fields like, to, from, message, to? what might be the reason? 
  #additionalScopes: []
      -messageRequest: Google_Service_Gmail_ModifyMessageRequest {#554 ▶}
      -swiftMessage: Swift_Message {#525 ▶}
      -parameters: []
      -message: null
      -subject: null
      -from: null
      -nameFrom: null
      -to: null
      -nameTo: null
      -cc: null
      -nameCc: null
      -bcc: null
      -nameBcc: null
      -attachments: []
      -priority: 2why dd is showing null for email related parameters?
how can I read my emails contents? this is our personal app and we need to access only our personal Gmail emails in our app. 
Do I need to enable additional scopes to read my emails in Laravel app ?
I published gmail.php in config folder using command, added additional scopes also, it's requesting additional scope, but still I am receiving null for email related fields when I dd
the $messages = LaravelGmail::message()->take(1)->all( $pageToken = null );
dd($messages);
all email related fields like, to, from, message are null in the array returned using dd

**Comment by martinschenk** [comment]
$messages = LaravelGmail::message()->take(1)->preload()->all( $pageToken = null );
shows you with dd a Mail id like f.e. '16ac632c5xxxxxx'
Now call
    $message = LaravelGmail::message()->get( '16ac632c5xxxxxx' );
    dump($message->getSubject());
    dump($message->getFromName());
    dump($message->getHtmlBody());
and so on...

**Comment by Luqman6666** [comment]
@martinschenk   dear, Now receiving this error

**Comment by Luqman6666** [comment]
@dacastro4     can anyone guide, why I am receiving this ? when I log in , Gmail asks me for permissions, I grant all permissions , read, write, view and delete email messages ? then why I am receiving 403 code ("forbidden error").  Infact I want to get list of emails of all senders , then I want to match the senders with a databse table called clients, if email of any sender matches with the database record , I wanna insert some data into a db table. Anyone can guide? how can I get list of emails of all senders ?

**Comment by dacastro4** [comment]
@Luqman6666 can you send me your scopes, they in the config/gmail.php or if you passed something in the custom during the request, those too.

**Comment by jaythegeek** [comment]
I am getting this too, I have the standard config and scopes, nothing extra, nothing less. I am getting the Metadata scope doesn't allow format FULL and also the Metadata scope does not support 'q' parameter depending on which query I am using. Very frustrating, cannot seem to figure this out

**Comment by dacastro4** [comment]
Ok, modify your scopes to 
```
'scopes' => [
	'readonly',
	'modify',
],
```

**Comment by dacastro4** [comment]
And also you have to log out and accept the permissions again

**Comment by jaythegeek** [comment]
That was it man, totally didn't think to logout, idiot move, I don't know why I didn't think of it... On another note, I am looking to expand this to sync calendar, I am working on it today so if I come up with some good stuff maybe we could chat about extending this package. :)
Thanks
J
