### ISSUE TITLE
Sending large files

### ISSUE THREAD

**Issue by igorhmelevskoy** [dacastro4/laravel-gmail#77]
Tell me how to send large files larger than 5 MB?
Here is my mistake
![1558417263816](https://user-images.githubusercontent.com/19838481/58071123-35dc6500-7ba4-11e9-9f89-c0cd6dee9b59.png)
In the documentation I found that I need to send as uploadType = resumable
Please tell me how this can be done?

**Comment by dacastro4** [comment]
Try using the method `optionalParameters`, it can be called from the message and takes an array and pass `['uploadType' => 'multipart']` and let me know.

Source: https://stackoverflow.com/questions/47679102/gmail-api-php-request-entity-too-large-error-413

**Comment by igorhmelevskoy** [comment]
> Try using the method `optionalParameters`, it can be called from the message and takes an array and pass `['uploadType' => 'multipart']` and let me know.
> 
> Source: https://stackoverflow.com/questions/47679102/gmail-api-php-request-entity-too-large-error-413

The error remains the same, I also tried to send via Google_Http_MediaFileUpload
by this decision
https://stackoverflow.com/questions/29081343/gmail-api-php-client-library-how-do-you-send-large-attachments-using-the-php-c
but the result remains the same, files of less than 5 MB in size are sent, all that produces an error more.
Most likely the solution is cost by sending through `uploadType = resumable`
https://developers.google.com/drive/api/v3/manage-uploads#resumable
