### ISSUE TITLE
Doesn't work with custom storage root path

### ISSUE THREAD

**Issue by avinash403** [dacastro4/laravel-gmail#78]
When storage root path in filesystem.php is changed to some custom path, it doesn't work.
It uses Storage facade to check if token file path exists in the system in GmailConnection.php.
But in Configurable.php, it directly uses storage_path. In case of custom path, both will not be same.

Check the screenshots below:
![Screenshot 2019-05-21 at 11 24 40 AM](https://user-images.githubusercontent.com/31030044/58071836-814e3d80-7bbb-11e9-818c-cdace9836a7a.png)
![Screenshot 2019-05-21 at 11 26 55 AM](https://user-images.githubusercontent.com/31030044/58071837-81e6d400-7bbb-11e9-87ad-0ce4d712a51a.png)
![Screenshot 2019-05-21 at 11 27 22 AM](https://user-images.githubusercontent.com/31030044/58071839-81e6d400-7bbb-11e9-8a15-bd7aa74c538e.png)

**Comment by dacastro4** [comment]
I see. you are right, I should be consistent. So you are saying to use `Storage` facade everything instead?

**Comment by avinash403** [comment]
Either of `Storage::disk('uploads')->get(...)` or `storage_path` would be fine. But it should be same everywhere. They can direct to different path in custom configuration like above.

**Comment by avinash403** [comment]
Another problem I am facing (I am sure other people will too) that path of the storage is using Storage facade to move attachments, which is not completely controllable from this package's configuration file. It would be nice to have a configuration for where it will store attachments. 

Actually, both attachment and token path could have been made controllable from the configuration file.

**Comment by dacastro4** [comment]
@avinash403 it is a really good idea
