### ISSUE TITLE
Class 'Dacastro4\LaravelGmail' not found

### ISSUE THREAD

**Issue by sbasi5576** [dacastro4/laravel-gmail#8]
I am getting the following error after following your installation steps.  I have entries in the app.php in the config directory for both class and alias and I have published it as well.

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Dacastro4\LaravelGmail' not found

Also see teh following:  
Symfony\Component\Debug\Exception\FatalThrowableError 
…/app/Http/Controllers/GmailController.php15

Controller code
<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Dacastro4\LaravelGmail;
 
class GmailController extends Controller
{
  
public function gmail()
{
    if (session_status() == PHP_SESSION_NONE) {
      session_start();
    }
 
$authUrl = LaravelGmail::getAuthUrl();
echo $authUrl;
exit();
 
 }
}

**Comment by dacastro4** [comment]
What version of Laravel are you using?

**Comment by sbasi5576** [comment]
5.6.  Actually, I used a different package to accomplish what I needed to.  Thanks.
