### ISSUE TITLE
Refresh Token not Refreshing on dev or prod

### ISSUE THREAD

**Issue by jaythegeek** [dacastro4/laravel-gmail#81]
Great work on the package! I am having a problem with the token refresh, it just doesnt seem to happen. On live or indeed on dev. It just expires after 3600. I saw there had been a fix but it is definitely not working. Any ideas?

**Comment by dacastro4** [comment]
@jaythegeek Which version are you using?

**Comment by jaythegeek** [comment]
Installed yesterday

**Comment by nasatome** [comment]
I am using version 1.0.6 and I have no problem, version 1.1 presents that problem?

**Comment by dacastro4** [comment]
@jaythegeek what have you tried? Did you try removing the file and login in again?
