### ISSUE TITLE
Problems with authentication

### ISSUE THREAD

**Issue by eagiraldor94** [dacastro4/laravel-gmail#83]
> I get the Google_Service_exception:401. "Login required".
Im calling LaravelGmail::redirect() when the user is logging to the app, but it seems that is not creating the token.
![image](https://user-images.githubusercontent.com/36866852/58518997-3c0bac00-8177-11e9-949e-42f3f4d69e8f.png)
![image](https://user-images.githubusercontent.com/36866852/58519007-44fc7d80-8177-11e9-8ac7-26de2cc71a1f.png)
![image](https://user-images.githubusercontent.com/36866852/58519011-4c238b80-8177-11e9-8441-22bf383172e1.png)
![image](https://user-images.githubusercontent.com/36866852/58519017-5180d600-8177-11e9-97d5-24d2049468b7.png)

**Comment by dacastro4** [comment]
@eagiraldor94 Does the callback URL matches the one in your Google console settings?

**Comment by jtwiest** [comment]
I'm having the same problem :frowning: Laravel 5.8.* and the latest version of this package.

**Comment by eagiraldor94** [comment]
the problem to me was that i called JSON "credentials.json", not "gmail-json.json"

**Comment by jtwiest** [comment]
Ah I got it working, I don't think I saw it anywhere in the help doc but eventually figured out I needed to create an empty file in the default locations of:

`/storage/app/gmail/tokens/gmail-json.json`

**Comment by dacastro4** [comment]
@jtwiest which it's weird. It should be automatically created. I'm going to add this information at the end of the readme that if you have problems logging in, create the `gmail-json.json` file.
Thank you

**Comment by damms005** [comment]
I guess you are referring to `GmailConnection.php#171-174`.

Since `Filesystem->put()` returns `bool`, why not do that check to ensure the file written to disk?
