### ISSUE TITLE
X-Attachment-Id needed for emails with embedded images

### ISSUE THREAD

**Issue by martinschenk** [dacastro4/laravel-gmail#84]
Emails which have embedded images, use as placeholder the X-Attachment-Id which is always in the header of the attachment part.
For example:

![Bildschirmfoto 2019-06-06 um 19 45 55](https://user-images.githubusercontent.com/635827/59054369-d2d11a80-8893-11e9-9334-03c36f0c4657.png)

It would be nice to have something like:

    $xAttachmentId = $attachment->headerDetails['X-Attachment-Id'];

Because otherwise its not possible to connect the image data with the embedded image.

I added some lines to Attachment.php to achieve it. It seems to work well:
1.) Variables

    /**
     * @var
     */
    public $headerDetails;
    /**
     * @var
     */
    private $headers;

2.) In the __contruct() i added
    
    $headers = $part->getHeaders();
    $this->headerDetails = $this->getHeaderDetails($headers);

3.) New function

    /**
     * Returns attachment headers
     * Contains Content-ID and X-Attachment-Id for embedded images
     *
     * @return array
     */
    public function getHeaderDetails($headers)
    {
        $headerDetails = [];
        foreach ($headers as $header){
            $headerDetails[$header->name] = $header->value;
        }
        return $headerDetails;
    }

@dacastro4 I will send a pull request with the changes. May be you are interested in adding this function. Or may be you know a better way to achieve the X-Attachment-Id.

**Comment by martinschenk** [comment]
Pull Request #85 added.

**Comment by martinschenk** [comment]
It can be called like this:
$headerDetails = $attachment->headerDetails[];

**Comment by dacastro4** [comment]
@martinschenk sorry for the delay. I understand the problem, I'm going to take a look at the PR. Thank you
