### ISSUE TITLE
Getting "No credentials found." auth exception

### ISSUE THREAD

**Issue by waqas767** [dacastro4/laravel-gmail#9]
I am getting  "No credentials found." auth exception on "LaravelGmail::message()->unread()->all()" after login(LaravelGmail::redirect()).

**Comment by dacastro4** [comment]
Hey @waqas767 . Can you check if you have a file on `storage/app/gmail/tokens`? What file driver are you using?

**Comment by sicaboy** [comment]
This project is not for CLI use.
