### ISSUE TITLE
403 error  displaying when using preload 

### ISSUE THREAD

**Issue by sudhanshuranjanAki** [dacastro4/laravel-gmail#90]
{ "error": { "errors": [ { "domain": "global", "reason": "forbidden", "message": "Metadata scope doesn't allow format FULL" } ], "code": 403, "message": "Metadata scope doesn't allow format FULL" } }

![image](https://user-images.githubusercontent.com/51784534/59490029-46c97f00-8ea1-11e9-9dfe-b7800f354c5b.png)

![image](https://user-images.githubusercontent.com/51784534/59490069-5a74e580-8ea1-11e9-861e-ba1b4fd8aaf4.png)

**Comment by dacastro4** [comment]
Did you check #83 ?

**Comment by pparesh13** [comment]
Remove the metadata option scope
