### ISSUE TITLE
Service accounts

### ISSUE THREAD

**Issue by rvkolosov** [dacastro4/laravel-gmail#95]
Hi, how I can use package with service accounts auth?

**Comment by dacastro4** [comment]
@rvkolosov I'm not familiar with service account auth. What do you need to accomplish that?

**Comment by rvkolosov** [comment]
@dacastro4 
I initially wanted to receive letters with attachments from the mailbox, and tried to use google api for this, but then I remembered imap and everything fell into place, thanks for the answer, you can close the issue
