### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by esmaily** [dacastro4/laravel-gmail#96]
1-After  install and config occer this error Error: redirect_uri_mismatch
2-but in local test work and connect to google on error ;
This app isn't verified
This app hasn't been verified by Google yet. Only proceed if you know and trust the develope

**Comment by dacastro4** [comment]
@esmaily what's the problem? That the app is not verified or that the uri is mismatching? If it's the latter, make sure that the URI matches in the Google Console and your website

**Comment by jesephan** [comment]
@esmaily make sure that your redirect uri is the same redirect uri that you provided when you generated the gmail api credentials
