### ISSUE TITLE
Reopen getHtmlBody() and getPlainTextBody() return NULL in some cases

### ISSUE THREAD

**Issue by samaphp** [dacastro4/laravel-gmail#98]
Thank you guys for fixing the main issue in #88, since there were some of the message types where I receive the body NULL but now it's fixed with v2.0. But, there is only one issue is still remain while I'm testing all kind of NULL email messages that I faced before. So, I believe this issue still exists in v2.0 in one case.
The HTML body is null when receiving an email from Mailchimp's service https://tinyletter.com This service is a free service to send newsletters.

Not sure what is the issue exactly but I'm getting the HTML body as NULL when I use getHtmlBody() even when using getPlainTextBody() too.
I just sent a one-line message with no inline photos.

<img width="1074" alt="Screenshot 2019-07-19 at 15 26 56" src="https://user-images.githubusercontent.com/531627/61534983-bea73e00-aa39-11e9-9079-144719d08304.png">

Thanks!

_Originally posted by @samaphp in https://github.com/dacastro4/laravel-gmail/issues/88#issuecomment-513211379_
Not sure why I can not reopen the issue #88 I think it may be because of reopening issues is restricted in this project.

**Comment by dacastro4** [comment]
That's interesting. Let me give it a try

**Comment by samaphp** [comment]
Hi Daniel, I just added you as a subscriber and sent an email to you.

The email subject is (Test Tinyletter email body issue)

**Comment by samaphp** [comment]
@dacastro4 One more thing I updated my version from 0.6.2 to 2.0.1. Then I faced that issue.
I'm trying to debug this issue now, but can you please give me any guidance in that? What exactly part that I can get a clean Message body before making it as parts using this library?

Thanks!

**Comment by dacastro4** [comment]
@samaphp hey I know it's been days and I'm sorry but I've been busy but I got some code that I'm testing and seems to be working. If everything goes right I'll release the patch on Monday

**Comment by samaphp** [comment]
Thank you @dacastro4 I really appreciate your efforts. and just replied here to provide help with debugging this issue :)
I will be glad if you can share anything for testing here.
Thanks again.

**Comment by samaphp** [comment]
Thank you @dacastro4 I just tried v2.0.3 and it is working well now. And I can get the message body correctly.

But I noticed this update broke `$message->sendToTrash()`.

The error because of the new line on this commit:
https://github.com/dacastro4/laravel-gmail/commit/fd29c6ca55c52f554ce162479316f67501bfb78e#diff-a0bc20268a7993d173f8632dd7ca0ca0R108

`$this->parts = collect($this->payload->getParts());`

Please find a screenshot

![Screenshot 2019-08-13 at 12 07 08](https://user-images.githubusercontent.com/531627/62929379-0ca62c00-bdc3-11e9-91ba-292de73f603e.png)

Thanks!

**Comment by dacastro4** [comment]
@samaphp I test it and you are right. Sorry about that. I just pushed the fix for this
