### ISSUE TITLE
How to paginate the mail and grouped by Thread?

### ISSUE THREAD

**Issue by PareshCitrusbug** [dacastro4/laravel-gmail#99]
I want to paginate email in the inbox but it is not working

$inbox = LaravelGmail::message()->in()->preload()->all();
$inbox->take(50);
$inbox->next();

![image](https://user-images.githubusercontent.com/45447854/61626724-a7678b00-ac9b-11e9-98c3-736ed438b213.png)

and if used
$inbox = LaravelGmail::message()->in()->preload();
            $inbox->take(50)->all();
            $inbox->next();
![image](https://user-images.githubusercontent.com/45447854/61626888-1513b700-ac9c-11e9-9ebc-2d156ceed133.png)

**Comment by dacastro4** [comment]
@PareshCitrusbug I could replicate the same screen. I'm working on this.

**Comment by dacastro4** [comment]
@PareshCitrusbug Do you mind checking if with the latest update this got resolved?

**Comment by MalindaWMD** [comment]
Hi, Seems like it still not working 

```
$inbox = LaravelGmail::message()
				->take(2)
				->from('noreply@medium.com')
				->unread()
				->preload();
$inbox->all();
dd($inbox->next());
```

![Screen Shot 2019-11-05 at 2 17 12 PM](https://user-images.githubusercontent.com/17429480/68192198-fe893580-ffd6-11e9-82d3-5f892876d686.png)

Please check

**Comment by dacastro4** [comment]
Regarding the grouping, you could try using the [groupBy](https://laravel.com/docs/5.8/collections#method-groupby) collection method on the `threadId` property.
